// Code generated by assertions generator; DO NOT EDIT.

package objectassert

import (
	"fmt"
	"testing"
	"time"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/helpers"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

type ComputePoolAssert struct {
	*assert.SnowflakeObjectAssert[sdk.ComputePool, sdk.AccountObjectIdentifier]
}

func ComputePool(t *testing.T, id sdk.AccountObjectIdentifier) *ComputePoolAssert {
	t.Helper()
	return &ComputePoolAssert{
		assert.NewSnowflakeObjectAssertWithTestClientObjectProvider(sdk.ObjectTypeComputePool, id, func(testClient *helpers.TestClient) assert.ObjectProvider[sdk.ComputePool, sdk.AccountObjectIdentifier] {
			return testClient.ComputePool.Show
		}),
	}
}

func ComputePoolFromObject(t *testing.T, computePool *sdk.ComputePool) *ComputePoolAssert {
	t.Helper()
	return &ComputePoolAssert{
		assert.NewSnowflakeObjectAssertWithObject(sdk.ObjectTypeComputePool, computePool.ID(), computePool),
	}
}

func (c *ComputePoolAssert) HasName(expected string) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.Name != expected {
			return fmt.Errorf("expected name: %v; got: %v", expected, o.Name)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasState(expected sdk.ComputePoolState) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.State != expected {
			return fmt.Errorf("expected state: %v; got: %v", expected, o.State)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasMinNodes(expected int) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.MinNodes != expected {
			return fmt.Errorf("expected min nodes: %v; got: %v", expected, o.MinNodes)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasMaxNodes(expected int) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.MaxNodes != expected {
			return fmt.Errorf("expected max nodes: %v; got: %v", expected, o.MaxNodes)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasInstanceFamily(expected sdk.ComputePoolInstanceFamily) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.InstanceFamily != expected {
			return fmt.Errorf("expected instance family: %v; got: %v", expected, o.InstanceFamily)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasNumServices(expected int) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.NumServices != expected {
			return fmt.Errorf("expected num services: %v; got: %v", expected, o.NumServices)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasNumJobs(expected int) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.NumJobs != expected {
			return fmt.Errorf("expected num jobs: %v; got: %v", expected, o.NumJobs)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasAutoSuspendSecs(expected int) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.AutoSuspendSecs != expected {
			return fmt.Errorf("expected auto suspend secs: %v; got: %v", expected, o.AutoSuspendSecs)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasAutoResume(expected bool) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.AutoResume != expected {
			return fmt.Errorf("expected auto resume: %v; got: %v", expected, o.AutoResume)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasActiveNodes(expected int) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.ActiveNodes != expected {
			return fmt.Errorf("expected active nodes: %v; got: %v", expected, o.ActiveNodes)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasIdleNodes(expected int) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.IdleNodes != expected {
			return fmt.Errorf("expected idle nodes: %v; got: %v", expected, o.IdleNodes)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasTargetNodes(expected int) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.TargetNodes != expected {
			return fmt.Errorf("expected target nodes: %v; got: %v", expected, o.TargetNodes)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasCreatedOn(expected time.Time) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.CreatedOn != expected {
			return fmt.Errorf("expected created on: %v; got: %v", expected, o.CreatedOn)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasResumedOn(expected time.Time) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.ResumedOn != expected {
			return fmt.Errorf("expected resumed on: %v; got: %v", expected, o.ResumedOn)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasUpdatedOn(expected time.Time) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.UpdatedOn != expected {
			return fmt.Errorf("expected updated on: %v; got: %v", expected, o.UpdatedOn)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasOwner(expected string) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.Owner != expected {
			return fmt.Errorf("expected owner: %v; got: %v", expected, o.Owner)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasComment(expected string) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.Comment == nil {
			return fmt.Errorf("expected comment to have value; got: nil")
		}
		if *o.Comment != expected {
			return fmt.Errorf("expected comment: %v; got: %v", expected, *o.Comment)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasIsExclusive(expected bool) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.IsExclusive != expected {
			return fmt.Errorf("expected is exclusive: %v; got: %v", expected, o.IsExclusive)
		}
		return nil
	})
	return c
}

func (c *ComputePoolAssert) HasApplication(expected sdk.AccountObjectIdentifier) *ComputePoolAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.ComputePool) error {
		t.Helper()
		if o.Application == nil {
			return fmt.Errorf("expected application to have value; got: nil")
		}
		if (*o.Application).Name() != expected.Name() {
			return fmt.Errorf("expected application: %v; got: %v", expected.Name(), (*o.Application).Name())
		}
		return nil
	})
	return c
}
