// Code generated by assertions generator; DO NOT EDIT.

package objectassert

import (
	"fmt"
	"testing"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

func (o *OrganizationAccountAssert) HasNoComment() *OrganizationAccountAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OrganizationAccount) error {
		t.Helper()
		if o.Comment != nil {
			return fmt.Errorf("expected comment to be nil, but got %s", *o.Comment)
		}
		return nil
	})
	return o
}
