// Code generated by sdk-to-schema generator; DO NOT EDIT.

package schemas

import (
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// ShowImageRepositorySchema represents output of SHOW query for the single ImageRepository.
var ShowImageRepositorySchema = map[string]*schema.Schema{
	"created_on": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"name": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"database_name": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"schema_name": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"repository_url": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"owner": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"owner_role_type": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"comment": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"privatelink_repository_url": {
		Type:     schema.TypeString,
		Computed: true,
	},
}

var _ = ShowImageRepositorySchema

func ImageRepositoryToSchema(imageRepository *sdk.ImageRepository) map[string]any {
	imageRepositorySchema := make(map[string]any)
	imageRepositorySchema["created_on"] = imageRepository.CreatedOn.String()
	imageRepositorySchema["name"] = imageRepository.Name
	imageRepositorySchema["database_name"] = imageRepository.DatabaseName
	imageRepositorySchema["schema_name"] = imageRepository.SchemaName
	imageRepositorySchema["repository_url"] = imageRepository.RepositoryUrl
	imageRepositorySchema["owner"] = imageRepository.Owner
	imageRepositorySchema["owner_role_type"] = imageRepository.OwnerRoleType
	imageRepositorySchema["comment"] = imageRepository.Comment
	imageRepositorySchema["privatelink_repository_url"] = imageRepository.PrivatelinkRepositoryUrl
	return imageRepositorySchema
}

var _ = ImageRepositoryToSchema
