// Code generated by sdk-to-schema generator; DO NOT EDIT.

package schemas

import (
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// ShowProgrammaticAccessTokenSchema represents output of SHOW query for the single ProgrammaticAccessToken.
var ShowProgrammaticAccessTokenSchema = map[string]*schema.Schema{
	"name": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"user_name": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"role_restriction": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"expires_at": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"status": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"comment": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"created_on": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"created_by": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"mins_to_bypass_network_policy_requirement": {
		Type:     schema.TypeInt,
		Computed: true,
	},
	"rotated_to": {
		Type:     schema.TypeString,
		Computed: true,
	},
}

var _ = ShowProgrammaticAccessTokenSchema

func ProgrammaticAccessTokenToSchema(programmaticAccessToken *sdk.ProgrammaticAccessToken) map[string]any {
	programmaticAccessTokenSchema := make(map[string]any)
	programmaticAccessTokenSchema["name"] = programmaticAccessToken.Name
	programmaticAccessTokenSchema["user_name"] = programmaticAccessToken.UserName.Name()
	if programmaticAccessToken.RoleRestriction != nil {
		programmaticAccessTokenSchema["role_restriction"] = programmaticAccessToken.RoleRestriction.Name()
	}
	programmaticAccessTokenSchema["expires_at"] = programmaticAccessToken.ExpiresAt.String()
	programmaticAccessTokenSchema["status"] = string(programmaticAccessToken.Status)
	if programmaticAccessToken.Comment != nil {
		programmaticAccessTokenSchema["comment"] = programmaticAccessToken.Comment
	}
	programmaticAccessTokenSchema["created_on"] = programmaticAccessToken.CreatedOn.String()
	programmaticAccessTokenSchema["created_by"] = programmaticAccessToken.CreatedBy
	if programmaticAccessToken.MinsToBypassNetworkPolicyRequirement != nil {
		programmaticAccessTokenSchema["mins_to_bypass_network_policy_requirement"] = programmaticAccessToken.MinsToBypassNetworkPolicyRequirement
	}
	if programmaticAccessToken.RotatedTo != nil {
		programmaticAccessTokenSchema["rotated_to"] = programmaticAccessToken.RotatedTo
	}
	return programmaticAccessTokenSchema
}

var _ = ProgrammaticAccessTokenToSchema
