// Code generated by config model builder generator; DO NOT EDIT.

package datasourcemodel

import (
	"encoding/json"

	tfconfig "github.com/hashicorp/terraform-plugin-testing/config"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/config"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/datasources"
)

type ServicesModel struct {
	In           tfconfig.Variable `json:"in,omitempty"`
	Like         tfconfig.Variable `json:"like,omitempty"`
	Limit        tfconfig.Variable `json:"limit,omitempty"`
	ServiceType  tfconfig.Variable `json:"service_type,omitempty"`
	Services     tfconfig.Variable `json:"services,omitempty"`
	StartsWith   tfconfig.Variable `json:"starts_with,omitempty"`
	WithDescribe tfconfig.Variable `json:"with_describe,omitempty"`

	*config.DatasourceModelMeta
}

/////////////////////////////////////////////////
// Basic builders (resource name and required) //
/////////////////////////////////////////////////

func Services(
	datasourceName string,
) *ServicesModel {
	s := &ServicesModel{DatasourceModelMeta: config.DatasourceMeta(datasourceName, datasources.Services)}
	return s
}

func ServicesWithDefaultMeta() *ServicesModel {
	s := &ServicesModel{DatasourceModelMeta: config.DatasourceDefaultMeta(datasources.Services)}
	return s
}

///////////////////////////////////////////////////////
// set proper json marshalling and handle depends on //
///////////////////////////////////////////////////////

func (s *ServicesModel) MarshalJSON() ([]byte, error) {
	type Alias ServicesModel
	return json.Marshal(&struct {
		*Alias
		DependsOn                 []string                      `json:"depends_on,omitempty"`
		SingleAttributeWorkaround config.ReplacementPlaceholder `json:"single_attribute_workaround,omitempty"`
	}{
		Alias:                     (*Alias)(s),
		DependsOn:                 s.DependsOn(),
		SingleAttributeWorkaround: config.SnowflakeProviderConfigSingleAttributeWorkaround,
	})
}

func (s *ServicesModel) WithDependsOn(values ...string) *ServicesModel {
	s.SetDependsOn(values...)
	return s
}

/////////////////////////////////
// below all the proper values //
/////////////////////////////////

// in attribute type is not yet supported, so WithIn can't be generated

func (s *ServicesModel) WithLike(like string) *ServicesModel {
	s.Like = tfconfig.StringVariable(like)
	return s
}

// limit attribute type is not yet supported, so WithLimit can't be generated

func (s *ServicesModel) WithServiceType(serviceType string) *ServicesModel {
	s.ServiceType = tfconfig.StringVariable(serviceType)
	return s
}

// services attribute type is not yet supported, so WithServices can't be generated

func (s *ServicesModel) WithStartsWith(startsWith string) *ServicesModel {
	s.StartsWith = tfconfig.StringVariable(startsWith)
	return s
}

func (s *ServicesModel) WithWithDescribe(withDescribe bool) *ServicesModel {
	s.WithDescribe = tfconfig.BoolVariable(withDescribe)
	return s
}

//////////////////////////////////////////
// below it's possible to set any value //
//////////////////////////////////////////

func (s *ServicesModel) WithInValue(value tfconfig.Variable) *ServicesModel {
	s.In = value
	return s
}

func (s *ServicesModel) WithLikeValue(value tfconfig.Variable) *ServicesModel {
	s.Like = value
	return s
}

func (s *ServicesModel) WithLimitValue(value tfconfig.Variable) *ServicesModel {
	s.Limit = value
	return s
}

func (s *ServicesModel) WithServiceTypeValue(value tfconfig.Variable) *ServicesModel {
	s.ServiceType = value
	return s
}

func (s *ServicesModel) WithServicesValue(value tfconfig.Variable) *ServicesModel {
	s.Services = value
	return s
}

func (s *ServicesModel) WithStartsWithValue(value tfconfig.Variable) *ServicesModel {
	s.StartsWith = value
	return s
}

func (s *ServicesModel) WithWithDescribeValue(value tfconfig.Variable) *ServicesModel {
	s.WithDescribe = value
	return s
}
