// Code generated by dto builder generator; DO NOT EDIT.

package sdk

import ()

func NewConfigFile() *ConfigFile {
	return &ConfigFile{}
}

func (s *ConfigFile) WithProfiles(Profiles map[string]ConfigDTO) *ConfigFile {
	s.Profiles = Profiles
	return s
}

func NewConfigDTO() *ConfigDTO {
	return &ConfigDTO{}
}

func (s *ConfigDTO) WithAccountName(AccountName string) *ConfigDTO {
	s.AccountName = &AccountName
	return s
}

func (s *ConfigDTO) WithOrganizationName(OrganizationName string) *ConfigDTO {
	s.OrganizationName = &OrganizationName
	return s
}

func (s *ConfigDTO) WithUser(User string) *ConfigDTO {
	s.User = &User
	return s
}

func (s *ConfigDTO) WithUsername(Username string) *ConfigDTO {
	s.Username = &Username
	return s
}

func (s *ConfigDTO) WithPassword(Password string) *ConfigDTO {
	s.Password = &Password
	return s
}

func (s *ConfigDTO) WithHost(Host string) *ConfigDTO {
	s.Host = &Host
	return s
}

func (s *ConfigDTO) WithWarehouse(Warehouse string) *ConfigDTO {
	s.Warehouse = &Warehouse
	return s
}

func (s *ConfigDTO) WithRole(Role string) *ConfigDTO {
	s.Role = &Role
	return s
}

func (s *ConfigDTO) WithParams(Params map[string]*string) *ConfigDTO {
	s.Params = &Params
	return s
}

func (s *ConfigDTO) WithClientIp(ClientIp string) *ConfigDTO {
	s.ClientIp = &ClientIp
	return s
}

func (s *ConfigDTO) WithProtocol(Protocol string) *ConfigDTO {
	s.Protocol = &Protocol
	return s
}

func (s *ConfigDTO) WithPasscode(Passcode string) *ConfigDTO {
	s.Passcode = &Passcode
	return s
}

func (s *ConfigDTO) WithPort(Port int) *ConfigDTO {
	s.Port = &Port
	return s
}

func (s *ConfigDTO) WithPasscodeInPassword(PasscodeInPassword bool) *ConfigDTO {
	s.PasscodeInPassword = &PasscodeInPassword
	return s
}

func (s *ConfigDTO) WithOktaUrl(OktaUrl string) *ConfigDTO {
	s.OktaUrl = &OktaUrl
	return s
}

func (s *ConfigDTO) WithClientTimeout(ClientTimeout int) *ConfigDTO {
	s.ClientTimeout = &ClientTimeout
	return s
}

func (s *ConfigDTO) WithJwtClientTimeout(JwtClientTimeout int) *ConfigDTO {
	s.JwtClientTimeout = &JwtClientTimeout
	return s
}

func (s *ConfigDTO) WithLoginTimeout(LoginTimeout int) *ConfigDTO {
	s.LoginTimeout = &LoginTimeout
	return s
}

func (s *ConfigDTO) WithRequestTimeout(RequestTimeout int) *ConfigDTO {
	s.RequestTimeout = &RequestTimeout
	return s
}

func (s *ConfigDTO) WithJwtExpireTimeout(JwtExpireTimeout int) *ConfigDTO {
	s.JwtExpireTimeout = &JwtExpireTimeout
	return s
}

func (s *ConfigDTO) WithExternalBrowserTimeout(ExternalBrowserTimeout int) *ConfigDTO {
	s.ExternalBrowserTimeout = &ExternalBrowserTimeout
	return s
}

func (s *ConfigDTO) WithMaxRetryCount(MaxRetryCount int) *ConfigDTO {
	s.MaxRetryCount = &MaxRetryCount
	return s
}

func (s *ConfigDTO) WithAuthenticator(Authenticator string) *ConfigDTO {
	s.Authenticator = &Authenticator
	return s
}

func (s *ConfigDTO) WithInsecureMode(InsecureMode bool) *ConfigDTO {
	s.InsecureMode = &InsecureMode
	return s
}

func (s *ConfigDTO) WithOcspFailOpen(OcspFailOpen bool) *ConfigDTO {
	s.OcspFailOpen = &OcspFailOpen
	return s
}

func (s *ConfigDTO) WithToken(Token string) *ConfigDTO {
	s.Token = &Token
	return s
}

func (s *ConfigDTO) WithKeepSessionAlive(KeepSessionAlive bool) *ConfigDTO {
	s.KeepSessionAlive = &KeepSessionAlive
	return s
}

func (s *ConfigDTO) WithPrivateKey(PrivateKey string) *ConfigDTO {
	s.PrivateKey = &PrivateKey
	return s
}

func (s *ConfigDTO) WithPrivateKeyPassphrase(PrivateKeyPassphrase string) *ConfigDTO {
	s.PrivateKeyPassphrase = &PrivateKeyPassphrase
	return s
}

func (s *ConfigDTO) WithDisableTelemetry(DisableTelemetry bool) *ConfigDTO {
	s.DisableTelemetry = &DisableTelemetry
	return s
}

func (s *ConfigDTO) WithValidateDefaultParameters(ValidateDefaultParameters bool) *ConfigDTO {
	s.ValidateDefaultParameters = &ValidateDefaultParameters
	return s
}

func (s *ConfigDTO) WithClientRequestMfaToken(ClientRequestMfaToken bool) *ConfigDTO {
	s.ClientRequestMfaToken = &ClientRequestMfaToken
	return s
}

func (s *ConfigDTO) WithClientStoreTemporaryCredential(ClientStoreTemporaryCredential bool) *ConfigDTO {
	s.ClientStoreTemporaryCredential = &ClientStoreTemporaryCredential
	return s
}

func (s *ConfigDTO) WithDriverTracing(DriverTracing string) *ConfigDTO {
	s.DriverTracing = &DriverTracing
	return s
}

func (s *ConfigDTO) WithTmpDirPath(TmpDirPath string) *ConfigDTO {
	s.TmpDirPath = &TmpDirPath
	return s
}

func (s *ConfigDTO) WithDisableQueryContextCache(DisableQueryContextCache bool) *ConfigDTO {
	s.DisableQueryContextCache = &DisableQueryContextCache
	return s
}

func (s *ConfigDTO) WithIncludeRetryReason(IncludeRetryReason bool) *ConfigDTO {
	s.IncludeRetryReason = &IncludeRetryReason
	return s
}

func (s *ConfigDTO) WithDisableConsoleLogin(DisableConsoleLogin bool) *ConfigDTO {
	s.DisableConsoleLogin = &DisableConsoleLogin
	return s
}
