// Code generated by dto builder generator; DO NOT EDIT.

package sdk

import ()

func NewCreateListingRequest(
	name AccountObjectIdentifier,
) *CreateListingRequest {
	s := CreateListingRequest{}
	s.name = name
	return &s
}

func (s *CreateListingRequest) WithIfNotExists(IfNotExists bool) *CreateListingRequest {
	s.IfNotExists = &IfNotExists
	return s
}

func (s *CreateListingRequest) WithWith(With ListingWithRequest) *CreateListingRequest {
	s.With = &With
	return s
}

func (s *CreateListingRequest) WithAs(As string) *CreateListingRequest {
	s.As = &As
	return s
}

func (s *CreateListingRequest) WithFrom(From Location) *CreateListingRequest {
	s.From = &From
	return s
}

func (s *CreateListingRequest) WithPublish(Publish bool) *CreateListingRequest {
	s.Publish = &Publish
	return s
}

func (s *CreateListingRequest) WithReview(Review bool) *CreateListingRequest {
	s.Review = &Review
	return s
}

func (s *CreateListingRequest) WithComment(Comment string) *CreateListingRequest {
	s.Comment = &Comment
	return s
}

func NewListingWithRequest() *ListingWithRequest {
	return &ListingWithRequest{}
}

func (s *ListingWithRequest) WithShare(Share AccountObjectIdentifier) *ListingWithRequest {
	s.Share = &Share
	return s
}

func (s *ListingWithRequest) WithApplicationPackage(ApplicationPackage AccountObjectIdentifier) *ListingWithRequest {
	s.ApplicationPackage = &ApplicationPackage
	return s
}

func NewAlterListingRequest(
	name AccountObjectIdentifier,
) *AlterListingRequest {
	s := AlterListingRequest{}
	s.name = name
	return &s
}

func (s *AlterListingRequest) WithIfExists(IfExists bool) *AlterListingRequest {
	s.IfExists = &IfExists
	return s
}

func (s *AlterListingRequest) WithPublish(Publish bool) *AlterListingRequest {
	s.Publish = &Publish
	return s
}

func (s *AlterListingRequest) WithUnpublish(Unpublish bool) *AlterListingRequest {
	s.Unpublish = &Unpublish
	return s
}

func (s *AlterListingRequest) WithReview(Review bool) *AlterListingRequest {
	s.Review = &Review
	return s
}

func (s *AlterListingRequest) WithAlterListingAs(AlterListingAs AlterListingAsRequest) *AlterListingRequest {
	s.AlterListingAs = &AlterListingAs
	return s
}

func (s *AlterListingRequest) WithAddVersion(AddVersion AddListingVersionRequest) *AlterListingRequest {
	s.AddVersion = &AddVersion
	return s
}

func (s *AlterListingRequest) WithRenameTo(RenameTo AccountObjectIdentifier) *AlterListingRequest {
	s.RenameTo = &RenameTo
	return s
}

func (s *AlterListingRequest) WithSet(Set ListingSetRequest) *AlterListingRequest {
	s.Set = &Set
	return s
}

func (s *AlterListingRequest) WithUnset(Unset ListingUnsetRequest) *AlterListingRequest {
	s.Unset = &Unset
	return s
}

func NewAlterListingAsRequest(
	As string,
) *AlterListingAsRequest {
	s := AlterListingAsRequest{}
	s.As = As
	return &s
}

func (s *AlterListingAsRequest) WithPublish(Publish bool) *AlterListingAsRequest {
	s.Publish = &Publish
	return s
}

func (s *AlterListingAsRequest) WithReview(Review bool) *AlterListingAsRequest {
	s.Review = &Review
	return s
}

func (s *AlterListingAsRequest) WithComment(Comment string) *AlterListingAsRequest {
	s.Comment = &Comment
	return s
}

func NewAddListingVersionRequest(
	VersionName string,
	From Location,
) *AddListingVersionRequest {
	s := AddListingVersionRequest{}
	s.VersionName = VersionName
	s.From = From
	return &s
}

func (s *AddListingVersionRequest) WithIfNotExists(IfNotExists bool) *AddListingVersionRequest {
	s.IfNotExists = &IfNotExists
	return s
}

func (s *AddListingVersionRequest) WithComment(Comment string) *AddListingVersionRequest {
	s.Comment = &Comment
	return s
}

func NewListingSetRequest() *ListingSetRequest {
	return &ListingSetRequest{}
}

func (s *ListingSetRequest) WithComment(Comment string) *ListingSetRequest {
	s.Comment = &Comment
	return s
}

func NewListingUnsetRequest() *ListingUnsetRequest {
	return &ListingUnsetRequest{}
}

func (s *ListingUnsetRequest) WithComment(Comment bool) *ListingUnsetRequest {
	s.Comment = &Comment
	return s
}

func NewDropListingRequest(
	name AccountObjectIdentifier,
) *DropListingRequest {
	s := DropListingRequest{}
	s.name = name
	return &s
}

func (s *DropListingRequest) WithIfExists(IfExists bool) *DropListingRequest {
	s.IfExists = &IfExists
	return s
}

func NewShowListingRequest() *ShowListingRequest {
	return &ShowListingRequest{}
}

func (s *ShowListingRequest) WithLike(Like Like) *ShowListingRequest {
	s.Like = &Like
	return s
}

func (s *ShowListingRequest) WithStartsWith(StartsWith string) *ShowListingRequest {
	s.StartsWith = &StartsWith
	return s
}

func (s *ShowListingRequest) WithLimit(Limit LimitFrom) *ShowListingRequest {
	s.Limit = &Limit
	return s
}

func NewDescribeListingRequest(
	name AccountObjectIdentifier,
) *DescribeListingRequest {
	s := DescribeListingRequest{}
	s.name = name
	return &s
}

func (s *DescribeListingRequest) WithRevision(Revision ListingRevision) *DescribeListingRequest {
	s.Revision = &Revision
	return s
}

func NewShowVersionsListingRequest(
	name AccountObjectIdentifier,
) *ShowVersionsListingRequest {
	s := ShowVersionsListingRequest{}
	s.name = name
	return &s
}

func (s *ShowVersionsListingRequest) WithLimit(Limit LimitFrom) *ShowVersionsListingRequest {
	s.Limit = &Limit
	return s
}
