// Code generated by dto builder generator; DO NOT EDIT.

package sdk

import ()

func NewCreateOrganizationAccountRequest(
	name AccountObjectIdentifier,
	AdminName string,
	Email string,
	Edition OrganizationAccountEdition,
) *CreateOrganizationAccountRequest {
	s := CreateOrganizationAccountRequest{}
	s.name = name
	s.AdminName = AdminName
	s.Email = Email
	s.Edition = Edition
	return &s
}

func (s *CreateOrganizationAccountRequest) WithAdminPassword(AdminPassword string) *CreateOrganizationAccountRequest {
	s.AdminPassword = &AdminPassword
	return s
}

func (s *CreateOrganizationAccountRequest) WithAdminRsaPublicKey(AdminRsaPublicKey string) *CreateOrganizationAccountRequest {
	s.AdminRsaPublicKey = &AdminRsaPublicKey
	return s
}

func (s *CreateOrganizationAccountRequest) WithFirstName(FirstName string) *CreateOrganizationAccountRequest {
	s.FirstName = &FirstName
	return s
}

func (s *CreateOrganizationAccountRequest) WithLastName(LastName string) *CreateOrganizationAccountRequest {
	s.LastName = &LastName
	return s
}

func (s *CreateOrganizationAccountRequest) WithMustChangePassword(MustChangePassword bool) *CreateOrganizationAccountRequest {
	s.MustChangePassword = &MustChangePassword
	return s
}

func (s *CreateOrganizationAccountRequest) WithRegionGroup(RegionGroup string) *CreateOrganizationAccountRequest {
	s.RegionGroup = &RegionGroup
	return s
}

func (s *CreateOrganizationAccountRequest) WithRegion(Region string) *CreateOrganizationAccountRequest {
	s.Region = &Region
	return s
}

func (s *CreateOrganizationAccountRequest) WithComment(Comment string) *CreateOrganizationAccountRequest {
	s.Comment = &Comment
	return s
}

func NewAlterOrganizationAccountRequest() *AlterOrganizationAccountRequest {
	return &AlterOrganizationAccountRequest{}
}

func (s *AlterOrganizationAccountRequest) WithName(Name AccountObjectIdentifier) *AlterOrganizationAccountRequest {
	s.Name = &Name
	return s
}

func (s *AlterOrganizationAccountRequest) WithSet(Set OrganizationAccountSetRequest) *AlterOrganizationAccountRequest {
	s.Set = &Set
	return s
}

func (s *AlterOrganizationAccountRequest) WithUnset(Unset OrganizationAccountUnsetRequest) *AlterOrganizationAccountRequest {
	s.Unset = &Unset
	return s
}

func (s *AlterOrganizationAccountRequest) WithSetTags(SetTags []TagAssociation) *AlterOrganizationAccountRequest {
	s.SetTags = SetTags
	return s
}

func (s *AlterOrganizationAccountRequest) WithUnsetTags(UnsetTags []ObjectIdentifier) *AlterOrganizationAccountRequest {
	s.UnsetTags = UnsetTags
	return s
}

func (s *AlterOrganizationAccountRequest) WithRenameTo(RenameTo OrganizationAccountRenameRequest) *AlterOrganizationAccountRequest {
	s.RenameTo = &RenameTo
	return s
}

func (s *AlterOrganizationAccountRequest) WithDropOldUrl(DropOldUrl bool) *AlterOrganizationAccountRequest {
	s.DropOldUrl = &DropOldUrl
	return s
}

func NewOrganizationAccountSetRequest() *OrganizationAccountSetRequest {
	return &OrganizationAccountSetRequest{}
}

func (s *OrganizationAccountSetRequest) WithParameters(Parameters AccountParameters) *OrganizationAccountSetRequest {
	s.Parameters = &Parameters
	return s
}

func (s *OrganizationAccountSetRequest) WithResourceMonitor(ResourceMonitor AccountObjectIdentifier) *OrganizationAccountSetRequest {
	s.ResourceMonitor = &ResourceMonitor
	return s
}

func (s *OrganizationAccountSetRequest) WithPasswordPolicy(PasswordPolicy SchemaObjectIdentifier) *OrganizationAccountSetRequest {
	s.PasswordPolicy = &PasswordPolicy
	return s
}

func (s *OrganizationAccountSetRequest) WithSessionPolicy(SessionPolicy SchemaObjectIdentifier) *OrganizationAccountSetRequest {
	s.SessionPolicy = &SessionPolicy
	return s
}

func (s *OrganizationAccountSetRequest) WithComment(Comment string) *OrganizationAccountSetRequest {
	s.Comment = &Comment
	return s
}

func NewOrganizationAccountUnsetRequest() *OrganizationAccountUnsetRequest {
	return &OrganizationAccountUnsetRequest{}
}

func (s *OrganizationAccountUnsetRequest) WithParameters(Parameters AccountParametersUnset) *OrganizationAccountUnsetRequest {
	s.Parameters = &Parameters
	return s
}

func (s *OrganizationAccountUnsetRequest) WithResourceMonitor(ResourceMonitor bool) *OrganizationAccountUnsetRequest {
	s.ResourceMonitor = &ResourceMonitor
	return s
}

func (s *OrganizationAccountUnsetRequest) WithPasswordPolicy(PasswordPolicy bool) *OrganizationAccountUnsetRequest {
	s.PasswordPolicy = &PasswordPolicy
	return s
}

func (s *OrganizationAccountUnsetRequest) WithSessionPolicy(SessionPolicy bool) *OrganizationAccountUnsetRequest {
	s.SessionPolicy = &SessionPolicy
	return s
}

func (s *OrganizationAccountUnsetRequest) WithComment(Comment bool) *OrganizationAccountUnsetRequest {
	s.Comment = &Comment
	return s
}

func NewOrganizationAccountRenameRequest(
	NewName *AccountObjectIdentifier,
) *OrganizationAccountRenameRequest {
	s := OrganizationAccountRenameRequest{}
	s.NewName = NewName
	return &s
}

func (s *OrganizationAccountRenameRequest) WithSaveOldUrl(SaveOldUrl bool) *OrganizationAccountRenameRequest {
	s.SaveOldUrl = &SaveOldUrl
	return s
}

func NewShowOrganizationAccountRequest() *ShowOrganizationAccountRequest {
	return &ShowOrganizationAccountRequest{}
}

func (s *ShowOrganizationAccountRequest) WithLike(Like Like) *ShowOrganizationAccountRequest {
	s.Like = &Like
	return s
}
