// Code generated by dto builder generator; DO NOT EDIT.

package sdk

import ()

func NewCreateServiceRequest(
	name SchemaObjectIdentifier,
	InComputePool AccountObjectIdentifier,
) *CreateServiceRequest {
	s := CreateServiceRequest{}
	s.name = name
	s.InComputePool = InComputePool
	return &s
}

func (s *CreateServiceRequest) WithIfNotExists(IfNotExists bool) *CreateServiceRequest {
	s.IfNotExists = &IfNotExists
	return s
}

func (s *CreateServiceRequest) WithFromSpecification(FromSpecification ServiceFromSpecificationRequest) *CreateServiceRequest {
	s.FromSpecification = &FromSpecification
	return s
}

func (s *CreateServiceRequest) WithFromSpecificationTemplate(FromSpecificationTemplate ServiceFromSpecificationTemplateRequest) *CreateServiceRequest {
	s.FromSpecificationTemplate = &FromSpecificationTemplate
	return s
}

func (s *CreateServiceRequest) WithAutoSuspendSecs(AutoSuspendSecs int) *CreateServiceRequest {
	s.AutoSuspendSecs = &AutoSuspendSecs
	return s
}

func (s *CreateServiceRequest) WithExternalAccessIntegrations(ExternalAccessIntegrations ServiceExternalAccessIntegrationsRequest) *CreateServiceRequest {
	s.ExternalAccessIntegrations = &ExternalAccessIntegrations
	return s
}

func (s *CreateServiceRequest) WithAutoResume(AutoResume bool) *CreateServiceRequest {
	s.AutoResume = &AutoResume
	return s
}

func (s *CreateServiceRequest) WithMinInstances(MinInstances int) *CreateServiceRequest {
	s.MinInstances = &MinInstances
	return s
}

func (s *CreateServiceRequest) WithMinReadyInstances(MinReadyInstances int) *CreateServiceRequest {
	s.MinReadyInstances = &MinReadyInstances
	return s
}

func (s *CreateServiceRequest) WithMaxInstances(MaxInstances int) *CreateServiceRequest {
	s.MaxInstances = &MaxInstances
	return s
}

func (s *CreateServiceRequest) WithQueryWarehouse(QueryWarehouse AccountObjectIdentifier) *CreateServiceRequest {
	s.QueryWarehouse = &QueryWarehouse
	return s
}

func (s *CreateServiceRequest) WithTag(Tag []TagAssociation) *CreateServiceRequest {
	s.Tag = Tag
	return s
}

func (s *CreateServiceRequest) WithComment(Comment string) *CreateServiceRequest {
	s.Comment = &Comment
	return s
}

func NewServiceFromSpecificationRequest() *ServiceFromSpecificationRequest {
	return &ServiceFromSpecificationRequest{}
}

func (s *ServiceFromSpecificationRequest) WithStage(Stage string) *ServiceFromSpecificationRequest {
	s.Stage = &Stage
	return s
}

func (s *ServiceFromSpecificationRequest) WithSpecificationFile(SpecificationFile string) *ServiceFromSpecificationRequest {
	s.SpecificationFile = &SpecificationFile
	return s
}

func (s *ServiceFromSpecificationRequest) WithSpecification(Specification string) *ServiceFromSpecificationRequest {
	s.Specification = &Specification
	return s
}

func NewServiceFromSpecificationTemplateRequest(
	Using []ListItem,
) *ServiceFromSpecificationTemplateRequest {
	s := ServiceFromSpecificationTemplateRequest{}
	s.Using = Using
	return &s
}

func (s *ServiceFromSpecificationTemplateRequest) WithStage(Stage string) *ServiceFromSpecificationTemplateRequest {
	s.Stage = &Stage
	return s
}

func (s *ServiceFromSpecificationTemplateRequest) WithSpecificationTemplateFile(SpecificationTemplateFile string) *ServiceFromSpecificationTemplateRequest {
	s.SpecificationTemplateFile = &SpecificationTemplateFile
	return s
}

func (s *ServiceFromSpecificationTemplateRequest) WithSpecificationTemplate(SpecificationTemplate string) *ServiceFromSpecificationTemplateRequest {
	s.SpecificationTemplate = &SpecificationTemplate
	return s
}

func NewServiceExternalAccessIntegrationsRequest(
	ExternalAccessIntegrations []AccountObjectIdentifier,
) *ServiceExternalAccessIntegrationsRequest {
	s := ServiceExternalAccessIntegrationsRequest{}
	s.ExternalAccessIntegrations = ExternalAccessIntegrations
	return &s
}

func NewAlterServiceRequest(
	name SchemaObjectIdentifier,
) *AlterServiceRequest {
	s := AlterServiceRequest{}
	s.name = name
	return &s
}

func (s *AlterServiceRequest) WithIfExists(IfExists bool) *AlterServiceRequest {
	s.IfExists = &IfExists
	return s
}

func (s *AlterServiceRequest) WithResume(Resume bool) *AlterServiceRequest {
	s.Resume = &Resume
	return s
}

func (s *AlterServiceRequest) WithSuspend(Suspend bool) *AlterServiceRequest {
	s.Suspend = &Suspend
	return s
}

func (s *AlterServiceRequest) WithFromSpecification(FromSpecification ServiceFromSpecificationRequest) *AlterServiceRequest {
	s.FromSpecification = &FromSpecification
	return s
}

func (s *AlterServiceRequest) WithFromSpecificationTemplate(FromSpecificationTemplate ServiceFromSpecificationTemplateRequest) *AlterServiceRequest {
	s.FromSpecificationTemplate = &FromSpecificationTemplate
	return s
}

func (s *AlterServiceRequest) WithRestore(Restore RestoreRequest) *AlterServiceRequest {
	s.Restore = &Restore
	return s
}

func (s *AlterServiceRequest) WithSet(Set ServiceSetRequest) *AlterServiceRequest {
	s.Set = &Set
	return s
}

func (s *AlterServiceRequest) WithUnset(Unset ServiceUnsetRequest) *AlterServiceRequest {
	s.Unset = &Unset
	return s
}

func (s *AlterServiceRequest) WithSetTags(SetTags []TagAssociation) *AlterServiceRequest {
	s.SetTags = SetTags
	return s
}

func (s *AlterServiceRequest) WithUnsetTags(UnsetTags []ObjectIdentifier) *AlterServiceRequest {
	s.UnsetTags = UnsetTags
	return s
}

func NewRestoreRequest(
	Volume string,
	Instances []int,
	FromSnapshot SchemaObjectIdentifier,
) *RestoreRequest {
	s := RestoreRequest{}
	s.Volume = Volume
	s.Instances = Instances
	s.FromSnapshot = FromSnapshot
	return &s
}

func NewServiceSetRequest() *ServiceSetRequest {
	return &ServiceSetRequest{}
}

func (s *ServiceSetRequest) WithMinInstances(MinInstances int) *ServiceSetRequest {
	s.MinInstances = &MinInstances
	return s
}

func (s *ServiceSetRequest) WithMaxInstances(MaxInstances int) *ServiceSetRequest {
	s.MaxInstances = &MaxInstances
	return s
}

func (s *ServiceSetRequest) WithAutoSuspendSecs(AutoSuspendSecs int) *ServiceSetRequest {
	s.AutoSuspendSecs = &AutoSuspendSecs
	return s
}

func (s *ServiceSetRequest) WithMinReadyInstances(MinReadyInstances int) *ServiceSetRequest {
	s.MinReadyInstances = &MinReadyInstances
	return s
}

func (s *ServiceSetRequest) WithQueryWarehouse(QueryWarehouse AccountObjectIdentifier) *ServiceSetRequest {
	s.QueryWarehouse = &QueryWarehouse
	return s
}

func (s *ServiceSetRequest) WithAutoResume(AutoResume bool) *ServiceSetRequest {
	s.AutoResume = &AutoResume
	return s
}

func (s *ServiceSetRequest) WithExternalAccessIntegrations(ExternalAccessIntegrations ServiceExternalAccessIntegrationsRequest) *ServiceSetRequest {
	s.ExternalAccessIntegrations = &ExternalAccessIntegrations
	return s
}

func (s *ServiceSetRequest) WithComment(Comment string) *ServiceSetRequest {
	s.Comment = &Comment
	return s
}

func NewServiceUnsetRequest() *ServiceUnsetRequest {
	return &ServiceUnsetRequest{}
}

func (s *ServiceUnsetRequest) WithMinInstances(MinInstances bool) *ServiceUnsetRequest {
	s.MinInstances = &MinInstances
	return s
}

func (s *ServiceUnsetRequest) WithAutoSuspendSecs(AutoSuspendSecs bool) *ServiceUnsetRequest {
	s.AutoSuspendSecs = &AutoSuspendSecs
	return s
}

func (s *ServiceUnsetRequest) WithMaxInstances(MaxInstances bool) *ServiceUnsetRequest {
	s.MaxInstances = &MaxInstances
	return s
}

func (s *ServiceUnsetRequest) WithMinReadyInstances(MinReadyInstances bool) *ServiceUnsetRequest {
	s.MinReadyInstances = &MinReadyInstances
	return s
}

func (s *ServiceUnsetRequest) WithQueryWarehouse(QueryWarehouse bool) *ServiceUnsetRequest {
	s.QueryWarehouse = &QueryWarehouse
	return s
}

func (s *ServiceUnsetRequest) WithAutoResume(AutoResume bool) *ServiceUnsetRequest {
	s.AutoResume = &AutoResume
	return s
}

func (s *ServiceUnsetRequest) WithExternalAccessIntegrations(ExternalAccessIntegrations bool) *ServiceUnsetRequest {
	s.ExternalAccessIntegrations = &ExternalAccessIntegrations
	return s
}

func (s *ServiceUnsetRequest) WithComment(Comment bool) *ServiceUnsetRequest {
	s.Comment = &Comment
	return s
}

func NewDropServiceRequest(
	name SchemaObjectIdentifier,
) *DropServiceRequest {
	s := DropServiceRequest{}
	s.name = name
	return &s
}

func (s *DropServiceRequest) WithIfExists(IfExists bool) *DropServiceRequest {
	s.IfExists = &IfExists
	return s
}

func (s *DropServiceRequest) WithForce(Force bool) *DropServiceRequest {
	s.Force = &Force
	return s
}

func NewShowServiceRequest() *ShowServiceRequest {
	return &ShowServiceRequest{}
}

func (s *ShowServiceRequest) WithJob(Job bool) *ShowServiceRequest {
	s.Job = &Job
	return s
}

func (s *ShowServiceRequest) WithExcludeJobs(ExcludeJobs bool) *ShowServiceRequest {
	s.ExcludeJobs = &ExcludeJobs
	return s
}

func (s *ShowServiceRequest) WithLike(Like Like) *ShowServiceRequest {
	s.Like = &Like
	return s
}

func (s *ShowServiceRequest) WithIn(In ServiceIn) *ShowServiceRequest {
	s.In = &In
	return s
}

func (s *ShowServiceRequest) WithStartsWith(StartsWith string) *ShowServiceRequest {
	s.StartsWith = &StartsWith
	return s
}

func (s *ShowServiceRequest) WithLimit(Limit LimitFrom) *ShowServiceRequest {
	s.Limit = &Limit
	return s
}

func NewDescribeServiceRequest(
	name SchemaObjectIdentifier,
) *DescribeServiceRequest {
	s := DescribeServiceRequest{}
	s.name = name
	return &s
}
