// Code generated by config model builder generator; DO NOT EDIT.

package model

import (
	"encoding/json"

	tfconfig "github.com/hashicorp/terraform-plugin-testing/config"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/config"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/resources"
)

type CurrentOrganizationAccountModel struct {
	AbortDetachedQuery                               tfconfig.Variable `json:"abort_detached_query,omitempty"`
	ActivePythonProfiler                             tfconfig.Variable `json:"active_python_profiler,omitempty"`
	AllowClientMfaCaching                            tfconfig.Variable `json:"allow_client_mfa_caching,omitempty"`
	AllowIdToken                                     tfconfig.Variable `json:"allow_id_token,omitempty"`
	Autocommit                                       tfconfig.Variable `json:"autocommit,omitempty"`
	BaseLocationPrefix                               tfconfig.Variable `json:"base_location_prefix,omitempty"`
	BinaryInputFormat                                tfconfig.Variable `json:"binary_input_format,omitempty"`
	BinaryOutputFormat                               tfconfig.Variable `json:"binary_output_format,omitempty"`
	Catalog                                          tfconfig.Variable `json:"catalog,omitempty"`
	CatalogSync                                      tfconfig.Variable `json:"catalog_sync,omitempty"`
	ClientEnableLogInfoStatementParameters           tfconfig.Variable `json:"client_enable_log_info_statement_parameters,omitempty"`
	ClientEncryptionKeySize                          tfconfig.Variable `json:"client_encryption_key_size,omitempty"`
	ClientMemoryLimit                                tfconfig.Variable `json:"client_memory_limit,omitempty"`
	ClientMetadataRequestUseConnectionCtx            tfconfig.Variable `json:"client_metadata_request_use_connection_ctx,omitempty"`
	ClientMetadataUseSessionDatabase                 tfconfig.Variable `json:"client_metadata_use_session_database,omitempty"`
	ClientPrefetchThreads                            tfconfig.Variable `json:"client_prefetch_threads,omitempty"`
	ClientResultChunkSize                            tfconfig.Variable `json:"client_result_chunk_size,omitempty"`
	ClientResultColumnCaseInsensitive                tfconfig.Variable `json:"client_result_column_case_insensitive,omitempty"`
	ClientSessionKeepAlive                           tfconfig.Variable `json:"client_session_keep_alive,omitempty"`
	ClientSessionKeepAliveHeartbeatFrequency         tfconfig.Variable `json:"client_session_keep_alive_heartbeat_frequency,omitempty"`
	ClientTimestampTypeMapping                       tfconfig.Variable `json:"client_timestamp_type_mapping,omitempty"`
	CortexEnabledCrossRegion                         tfconfig.Variable `json:"cortex_enabled_cross_region,omitempty"`
	CortexModelsAllowlist                            tfconfig.Variable `json:"cortex_models_allowlist,omitempty"`
	CsvTimestampFormat                               tfconfig.Variable `json:"csv_timestamp_format,omitempty"`
	DataRetentionTimeInDays                          tfconfig.Variable `json:"data_retention_time_in_days,omitempty"`
	DateInputFormat                                  tfconfig.Variable `json:"date_input_format,omitempty"`
	DateOutputFormat                                 tfconfig.Variable `json:"date_output_format,omitempty"`
	DefaultDdlCollation                              tfconfig.Variable `json:"default_ddl_collation,omitempty"`
	DefaultNotebookComputePoolCpu                    tfconfig.Variable `json:"default_notebook_compute_pool_cpu,omitempty"`
	DefaultNotebookComputePoolGpu                    tfconfig.Variable `json:"default_notebook_compute_pool_gpu,omitempty"`
	DefaultNullOrdering                              tfconfig.Variable `json:"default_null_ordering,omitempty"`
	DefaultStreamlitNotebookWarehouse                tfconfig.Variable `json:"default_streamlit_notebook_warehouse,omitempty"`
	DisableUiDownloadButton                          tfconfig.Variable `json:"disable_ui_download_button,omitempty"`
	DisableUserPrivilegeGrants                       tfconfig.Variable `json:"disable_user_privilege_grants,omitempty"`
	EnableAutomaticSensitiveDataClassificationLog    tfconfig.Variable `json:"enable_automatic_sensitive_data_classification_log,omitempty"`
	EnableEgressCostOptimizer                        tfconfig.Variable `json:"enable_egress_cost_optimizer,omitempty"`
	EnableIdentifierFirstLogin                       tfconfig.Variable `json:"enable_identifier_first_login,omitempty"`
	EnableInternalStagesPrivatelink                  tfconfig.Variable `json:"enable_internal_stages_privatelink,omitempty"`
	EnableTriSecretAndRekeyOptOutForImageRepository  tfconfig.Variable `json:"enable_tri_secret_and_rekey_opt_out_for_image_repository,omitempty"`
	EnableTriSecretAndRekeyOptOutForSpcsBlockStorage tfconfig.Variable `json:"enable_tri_secret_and_rekey_opt_out_for_spcs_block_storage,omitempty"`
	EnableUnhandledExceptionsReporting               tfconfig.Variable `json:"enable_unhandled_exceptions_reporting,omitempty"`
	EnableUnloadPhysicalTypeOptimization             tfconfig.Variable `json:"enable_unload_physical_type_optimization,omitempty"`
	EnableUnredactedQuerySyntaxError                 tfconfig.Variable `json:"enable_unredacted_query_syntax_error,omitempty"`
	EnableUnredactedSecureObjectError                tfconfig.Variable `json:"enable_unredacted_secure_object_error,omitempty"`
	EnforceNetworkRulesForInternalStages             tfconfig.Variable `json:"enforce_network_rules_for_internal_stages,omitempty"`
	ErrorOnNondeterministicMerge                     tfconfig.Variable `json:"error_on_nondeterministic_merge,omitempty"`
	ErrorOnNondeterministicUpdate                    tfconfig.Variable `json:"error_on_nondeterministic_update,omitempty"`
	EventTable                                       tfconfig.Variable `json:"event_table,omitempty"`
	ExternalOauthAddPrivilegedRolesToBlockedList     tfconfig.Variable `json:"external_oauth_add_privileged_roles_to_blocked_list,omitempty"`
	ExternalVolume                                   tfconfig.Variable `json:"external_volume,omitempty"`
	GeographyOutputFormat                            tfconfig.Variable `json:"geography_output_format,omitempty"`
	GeometryOutputFormat                             tfconfig.Variable `json:"geometry_output_format,omitempty"`
	HybridTableLockTimeout                           tfconfig.Variable `json:"hybrid_table_lock_timeout,omitempty"`
	InitialReplicationSizeLimitInTb                  tfconfig.Variable `json:"initial_replication_size_limit_in_tb,omitempty"`
	JdbcTreatDecimalAsInt                            tfconfig.Variable `json:"jdbc_treat_decimal_as_int,omitempty"`
	JdbcTreatTimestampNtzAsUtc                       tfconfig.Variable `json:"jdbc_treat_timestamp_ntz_as_utc,omitempty"`
	JdbcUseSessionTimezone                           tfconfig.Variable `json:"jdbc_use_session_timezone,omitempty"`
	JsTreatIntegerAsBigint                           tfconfig.Variable `json:"js_treat_integer_as_bigint,omitempty"`
	JsonIndent                                       tfconfig.Variable `json:"json_indent,omitempty"`
	ListingAutoFulfillmentReplicationRefreshSchedule tfconfig.Variable `json:"listing_auto_fulfillment_replication_refresh_schedule,omitempty"`
	LockTimeout                                      tfconfig.Variable `json:"lock_timeout,omitempty"`
	LogLevel                                         tfconfig.Variable `json:"log_level,omitempty"`
	MaxConcurrencyLevel                              tfconfig.Variable `json:"max_concurrency_level,omitempty"`
	MaxDataExtensionTimeInDays                       tfconfig.Variable `json:"max_data_extension_time_in_days,omitempty"`
	MetricLevel                                      tfconfig.Variable `json:"metric_level,omitempty"`
	MinDataRetentionTimeInDays                       tfconfig.Variable `json:"min_data_retention_time_in_days,omitempty"`
	MultiStatementCount                              tfconfig.Variable `json:"multi_statement_count,omitempty"`
	NetworkPolicy                                    tfconfig.Variable `json:"network_policy,omitempty"`
	NoorderSequenceAsDefault                         tfconfig.Variable `json:"noorder_sequence_as_default,omitempty"`
	OauthAddPrivilegedRolesToBlockedList             tfconfig.Variable `json:"oauth_add_privileged_roles_to_blocked_list,omitempty"`
	OdbcTreatDecimalAsInt                            tfconfig.Variable `json:"odbc_treat_decimal_as_int,omitempty"`
	PasswordPolicy                                   tfconfig.Variable `json:"password_policy,omitempty"`
	PeriodicDataRekeying                             tfconfig.Variable `json:"periodic_data_rekeying,omitempty"`
	PipeExecutionPaused                              tfconfig.Variable `json:"pipe_execution_paused,omitempty"`
	PreventUnloadToInlineUrl                         tfconfig.Variable `json:"prevent_unload_to_inline_url,omitempty"`
	PreventUnloadToInternalStages                    tfconfig.Variable `json:"prevent_unload_to_internal_stages,omitempty"`
	PythonProfilerModules                            tfconfig.Variable `json:"python_profiler_modules,omitempty"`
	PythonProfilerTargetStage                        tfconfig.Variable `json:"python_profiler_target_stage,omitempty"`
	QueryTag                                         tfconfig.Variable `json:"query_tag,omitempty"`
	QuotedIdentifiersIgnoreCase                      tfconfig.Variable `json:"quoted_identifiers_ignore_case,omitempty"`
	ReplaceInvalidCharacters                         tfconfig.Variable `json:"replace_invalid_characters,omitempty"`
	RequireStorageIntegrationForStageCreation        tfconfig.Variable `json:"require_storage_integration_for_stage_creation,omitempty"`
	RequireStorageIntegrationForStageOperation       tfconfig.Variable `json:"require_storage_integration_for_stage_operation,omitempty"`
	ResourceMonitor                                  tfconfig.Variable `json:"resource_monitor,omitempty"`
	RowsPerResultset                                 tfconfig.Variable `json:"rows_per_resultset,omitempty"`
	S3StageVpceDnsName                               tfconfig.Variable `json:"s3_stage_vpce_dns_name,omitempty"`
	SamlIdentityProvider                             tfconfig.Variable `json:"saml_identity_provider,omitempty"`
	SearchPath                                       tfconfig.Variable `json:"search_path,omitempty"`
	ServerlessTaskMaxStatementSize                   tfconfig.Variable `json:"serverless_task_max_statement_size,omitempty"`
	ServerlessTaskMinStatementSize                   tfconfig.Variable `json:"serverless_task_min_statement_size,omitempty"`
	SessionPolicy                                    tfconfig.Variable `json:"session_policy,omitempty"`
	SimulatedDataSharingConsumer                     tfconfig.Variable `json:"simulated_data_sharing_consumer,omitempty"`
	SsoLoginPage                                     tfconfig.Variable `json:"sso_login_page,omitempty"`
	StatementQueuedTimeoutInSeconds                  tfconfig.Variable `json:"statement_queued_timeout_in_seconds,omitempty"`
	StatementTimeoutInSeconds                        tfconfig.Variable `json:"statement_timeout_in_seconds,omitempty"`
	StorageSerializationPolicy                       tfconfig.Variable `json:"storage_serialization_policy,omitempty"`
	StrictJsonOutput                                 tfconfig.Variable `json:"strict_json_output,omitempty"`
	SuspendTaskAfterNumFailures                      tfconfig.Variable `json:"suspend_task_after_num_failures,omitempty"`
	TaskAutoRetryAttempts                            tfconfig.Variable `json:"task_auto_retry_attempts,omitempty"`
	TimeInputFormat                                  tfconfig.Variable `json:"time_input_format,omitempty"`
	TimeOutputFormat                                 tfconfig.Variable `json:"time_output_format,omitempty"`
	TimestampDayIsAlways24h                          tfconfig.Variable `json:"timestamp_day_is_always_24h,omitempty"`
	TimestampInputFormat                             tfconfig.Variable `json:"timestamp_input_format,omitempty"`
	TimestampLtzOutputFormat                         tfconfig.Variable `json:"timestamp_ltz_output_format,omitempty"`
	TimestampNtzOutputFormat                         tfconfig.Variable `json:"timestamp_ntz_output_format,omitempty"`
	TimestampOutputFormat                            tfconfig.Variable `json:"timestamp_output_format,omitempty"`
	TimestampTypeMapping                             tfconfig.Variable `json:"timestamp_type_mapping,omitempty"`
	TimestampTzOutputFormat                          tfconfig.Variable `json:"timestamp_tz_output_format,omitempty"`
	Timezone                                         tfconfig.Variable `json:"timezone,omitempty"`
	TraceLevel                                       tfconfig.Variable `json:"trace_level,omitempty"`
	TransactionAbortOnError                          tfconfig.Variable `json:"transaction_abort_on_error,omitempty"`
	TransactionDefaultIsolationLevel                 tfconfig.Variable `json:"transaction_default_isolation_level,omitempty"`
	TwoDigitCenturyStart                             tfconfig.Variable `json:"two_digit_century_start,omitempty"`
	UnsupportedDdlAction                             tfconfig.Variable `json:"unsupported_ddl_action,omitempty"`
	UseCachedResult                                  tfconfig.Variable `json:"use_cached_result,omitempty"`
	UserTaskManagedInitialWarehouseSize              tfconfig.Variable `json:"user_task_managed_initial_warehouse_size,omitempty"`
	UserTaskMinimumTriggerIntervalInSeconds          tfconfig.Variable `json:"user_task_minimum_trigger_interval_in_seconds,omitempty"`
	UserTaskTimeoutMs                                tfconfig.Variable `json:"user_task_timeout_ms,omitempty"`
	WeekOfYearPolicy                                 tfconfig.Variable `json:"week_of_year_policy,omitempty"`
	WeekStart                                        tfconfig.Variable `json:"week_start,omitempty"`

	DynamicBlock *config.DynamicBlock `json:"dynamic,omitempty"`

	*config.ResourceModelMeta
}

/////////////////////////////////////////////////
// Basic builders (resource name and required) //
/////////////////////////////////////////////////

func CurrentOrganizationAccount(
	resourceName string,
) *CurrentOrganizationAccountModel {
	c := &CurrentOrganizationAccountModel{ResourceModelMeta: config.Meta(resourceName, resources.CurrentOrganizationAccount)}
	return c
}

func CurrentOrganizationAccountWithDefaultMeta() *CurrentOrganizationAccountModel {
	c := &CurrentOrganizationAccountModel{ResourceModelMeta: config.DefaultMeta(resources.CurrentOrganizationAccount)}
	return c
}

///////////////////////////////////////////////////////////////////////
// set proper json marshalling, handle depends on and dynamic blocks //
///////////////////////////////////////////////////////////////////////

func (c *CurrentOrganizationAccountModel) MarshalJSON() ([]byte, error) {
	type Alias CurrentOrganizationAccountModel
	return json.Marshal(&struct {
		*Alias
		DependsOn []string `json:"depends_on,omitempty"`
	}{
		Alias:     (*Alias)(c),
		DependsOn: c.DependsOn(),
	})
}

func (c *CurrentOrganizationAccountModel) WithDependsOn(values ...string) *CurrentOrganizationAccountModel {
	c.SetDependsOn(values...)
	return c
}

func (c *CurrentOrganizationAccountModel) WithDynamicBlock(dynamicBlock *config.DynamicBlock) *CurrentOrganizationAccountModel {
	c.DynamicBlock = dynamicBlock
	return c
}

/////////////////////////////////
// below all the proper values //
/////////////////////////////////

func (c *CurrentOrganizationAccountModel) WithAbortDetachedQuery(abortDetachedQuery bool) *CurrentOrganizationAccountModel {
	c.AbortDetachedQuery = tfconfig.BoolVariable(abortDetachedQuery)
	return c
}

func (c *CurrentOrganizationAccountModel) WithActivePythonProfiler(activePythonProfiler string) *CurrentOrganizationAccountModel {
	c.ActivePythonProfiler = tfconfig.StringVariable(activePythonProfiler)
	return c
}

func (c *CurrentOrganizationAccountModel) WithAllowClientMfaCaching(allowClientMfaCaching bool) *CurrentOrganizationAccountModel {
	c.AllowClientMfaCaching = tfconfig.BoolVariable(allowClientMfaCaching)
	return c
}

func (c *CurrentOrganizationAccountModel) WithAllowIdToken(allowIdToken bool) *CurrentOrganizationAccountModel {
	c.AllowIdToken = tfconfig.BoolVariable(allowIdToken)
	return c
}

func (c *CurrentOrganizationAccountModel) WithAutocommit(autocommit bool) *CurrentOrganizationAccountModel {
	c.Autocommit = tfconfig.BoolVariable(autocommit)
	return c
}

func (c *CurrentOrganizationAccountModel) WithBaseLocationPrefix(baseLocationPrefix string) *CurrentOrganizationAccountModel {
	c.BaseLocationPrefix = tfconfig.StringVariable(baseLocationPrefix)
	return c
}

func (c *CurrentOrganizationAccountModel) WithBinaryInputFormat(binaryInputFormat string) *CurrentOrganizationAccountModel {
	c.BinaryInputFormat = tfconfig.StringVariable(binaryInputFormat)
	return c
}

func (c *CurrentOrganizationAccountModel) WithBinaryOutputFormat(binaryOutputFormat string) *CurrentOrganizationAccountModel {
	c.BinaryOutputFormat = tfconfig.StringVariable(binaryOutputFormat)
	return c
}

func (c *CurrentOrganizationAccountModel) WithCatalog(catalog string) *CurrentOrganizationAccountModel {
	c.Catalog = tfconfig.StringVariable(catalog)
	return c
}

func (c *CurrentOrganizationAccountModel) WithCatalogSync(catalogSync string) *CurrentOrganizationAccountModel {
	c.CatalogSync = tfconfig.StringVariable(catalogSync)
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientEnableLogInfoStatementParameters(clientEnableLogInfoStatementParameters bool) *CurrentOrganizationAccountModel {
	c.ClientEnableLogInfoStatementParameters = tfconfig.BoolVariable(clientEnableLogInfoStatementParameters)
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientEncryptionKeySize(clientEncryptionKeySize int) *CurrentOrganizationAccountModel {
	c.ClientEncryptionKeySize = tfconfig.IntegerVariable(clientEncryptionKeySize)
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientMemoryLimit(clientMemoryLimit int) *CurrentOrganizationAccountModel {
	c.ClientMemoryLimit = tfconfig.IntegerVariable(clientMemoryLimit)
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientMetadataRequestUseConnectionCtx(clientMetadataRequestUseConnectionCtx bool) *CurrentOrganizationAccountModel {
	c.ClientMetadataRequestUseConnectionCtx = tfconfig.BoolVariable(clientMetadataRequestUseConnectionCtx)
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientMetadataUseSessionDatabase(clientMetadataUseSessionDatabase bool) *CurrentOrganizationAccountModel {
	c.ClientMetadataUseSessionDatabase = tfconfig.BoolVariable(clientMetadataUseSessionDatabase)
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientPrefetchThreads(clientPrefetchThreads int) *CurrentOrganizationAccountModel {
	c.ClientPrefetchThreads = tfconfig.IntegerVariable(clientPrefetchThreads)
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientResultChunkSize(clientResultChunkSize int) *CurrentOrganizationAccountModel {
	c.ClientResultChunkSize = tfconfig.IntegerVariable(clientResultChunkSize)
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientResultColumnCaseInsensitive(clientResultColumnCaseInsensitive bool) *CurrentOrganizationAccountModel {
	c.ClientResultColumnCaseInsensitive = tfconfig.BoolVariable(clientResultColumnCaseInsensitive)
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientSessionKeepAlive(clientSessionKeepAlive bool) *CurrentOrganizationAccountModel {
	c.ClientSessionKeepAlive = tfconfig.BoolVariable(clientSessionKeepAlive)
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientSessionKeepAliveHeartbeatFrequency(clientSessionKeepAliveHeartbeatFrequency int) *CurrentOrganizationAccountModel {
	c.ClientSessionKeepAliveHeartbeatFrequency = tfconfig.IntegerVariable(clientSessionKeepAliveHeartbeatFrequency)
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientTimestampTypeMapping(clientTimestampTypeMapping string) *CurrentOrganizationAccountModel {
	c.ClientTimestampTypeMapping = tfconfig.StringVariable(clientTimestampTypeMapping)
	return c
}

func (c *CurrentOrganizationAccountModel) WithCortexEnabledCrossRegion(cortexEnabledCrossRegion string) *CurrentOrganizationAccountModel {
	c.CortexEnabledCrossRegion = tfconfig.StringVariable(cortexEnabledCrossRegion)
	return c
}

func (c *CurrentOrganizationAccountModel) WithCortexModelsAllowlist(cortexModelsAllowlist string) *CurrentOrganizationAccountModel {
	c.CortexModelsAllowlist = tfconfig.StringVariable(cortexModelsAllowlist)
	return c
}

func (c *CurrentOrganizationAccountModel) WithCsvTimestampFormat(csvTimestampFormat string) *CurrentOrganizationAccountModel {
	c.CsvTimestampFormat = tfconfig.StringVariable(csvTimestampFormat)
	return c
}

func (c *CurrentOrganizationAccountModel) WithDataRetentionTimeInDays(dataRetentionTimeInDays int) *CurrentOrganizationAccountModel {
	c.DataRetentionTimeInDays = tfconfig.IntegerVariable(dataRetentionTimeInDays)
	return c
}

func (c *CurrentOrganizationAccountModel) WithDateInputFormat(dateInputFormat string) *CurrentOrganizationAccountModel {
	c.DateInputFormat = tfconfig.StringVariable(dateInputFormat)
	return c
}

func (c *CurrentOrganizationAccountModel) WithDateOutputFormat(dateOutputFormat string) *CurrentOrganizationAccountModel {
	c.DateOutputFormat = tfconfig.StringVariable(dateOutputFormat)
	return c
}

func (c *CurrentOrganizationAccountModel) WithDefaultDdlCollation(defaultDdlCollation string) *CurrentOrganizationAccountModel {
	c.DefaultDdlCollation = tfconfig.StringVariable(defaultDdlCollation)
	return c
}

func (c *CurrentOrganizationAccountModel) WithDefaultNotebookComputePoolCpu(defaultNotebookComputePoolCpu string) *CurrentOrganizationAccountModel {
	c.DefaultNotebookComputePoolCpu = tfconfig.StringVariable(defaultNotebookComputePoolCpu)
	return c
}

func (c *CurrentOrganizationAccountModel) WithDefaultNotebookComputePoolGpu(defaultNotebookComputePoolGpu string) *CurrentOrganizationAccountModel {
	c.DefaultNotebookComputePoolGpu = tfconfig.StringVariable(defaultNotebookComputePoolGpu)
	return c
}

func (c *CurrentOrganizationAccountModel) WithDefaultNullOrdering(defaultNullOrdering string) *CurrentOrganizationAccountModel {
	c.DefaultNullOrdering = tfconfig.StringVariable(defaultNullOrdering)
	return c
}

func (c *CurrentOrganizationAccountModel) WithDefaultStreamlitNotebookWarehouse(defaultStreamlitNotebookWarehouse string) *CurrentOrganizationAccountModel {
	c.DefaultStreamlitNotebookWarehouse = tfconfig.StringVariable(defaultStreamlitNotebookWarehouse)
	return c
}

func (c *CurrentOrganizationAccountModel) WithDisableUiDownloadButton(disableUiDownloadButton bool) *CurrentOrganizationAccountModel {
	c.DisableUiDownloadButton = tfconfig.BoolVariable(disableUiDownloadButton)
	return c
}

func (c *CurrentOrganizationAccountModel) WithDisableUserPrivilegeGrants(disableUserPrivilegeGrants bool) *CurrentOrganizationAccountModel {
	c.DisableUserPrivilegeGrants = tfconfig.BoolVariable(disableUserPrivilegeGrants)
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableAutomaticSensitiveDataClassificationLog(enableAutomaticSensitiveDataClassificationLog bool) *CurrentOrganizationAccountModel {
	c.EnableAutomaticSensitiveDataClassificationLog = tfconfig.BoolVariable(enableAutomaticSensitiveDataClassificationLog)
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableEgressCostOptimizer(enableEgressCostOptimizer bool) *CurrentOrganizationAccountModel {
	c.EnableEgressCostOptimizer = tfconfig.BoolVariable(enableEgressCostOptimizer)
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableIdentifierFirstLogin(enableIdentifierFirstLogin bool) *CurrentOrganizationAccountModel {
	c.EnableIdentifierFirstLogin = tfconfig.BoolVariable(enableIdentifierFirstLogin)
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableInternalStagesPrivatelink(enableInternalStagesPrivatelink bool) *CurrentOrganizationAccountModel {
	c.EnableInternalStagesPrivatelink = tfconfig.BoolVariable(enableInternalStagesPrivatelink)
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableTriSecretAndRekeyOptOutForImageRepository(enableTriSecretAndRekeyOptOutForImageRepository bool) *CurrentOrganizationAccountModel {
	c.EnableTriSecretAndRekeyOptOutForImageRepository = tfconfig.BoolVariable(enableTriSecretAndRekeyOptOutForImageRepository)
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableTriSecretAndRekeyOptOutForSpcsBlockStorage(enableTriSecretAndRekeyOptOutForSpcsBlockStorage bool) *CurrentOrganizationAccountModel {
	c.EnableTriSecretAndRekeyOptOutForSpcsBlockStorage = tfconfig.BoolVariable(enableTriSecretAndRekeyOptOutForSpcsBlockStorage)
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableUnhandledExceptionsReporting(enableUnhandledExceptionsReporting bool) *CurrentOrganizationAccountModel {
	c.EnableUnhandledExceptionsReporting = tfconfig.BoolVariable(enableUnhandledExceptionsReporting)
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableUnloadPhysicalTypeOptimization(enableUnloadPhysicalTypeOptimization bool) *CurrentOrganizationAccountModel {
	c.EnableUnloadPhysicalTypeOptimization = tfconfig.BoolVariable(enableUnloadPhysicalTypeOptimization)
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableUnredactedQuerySyntaxError(enableUnredactedQuerySyntaxError bool) *CurrentOrganizationAccountModel {
	c.EnableUnredactedQuerySyntaxError = tfconfig.BoolVariable(enableUnredactedQuerySyntaxError)
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableUnredactedSecureObjectError(enableUnredactedSecureObjectError bool) *CurrentOrganizationAccountModel {
	c.EnableUnredactedSecureObjectError = tfconfig.BoolVariable(enableUnredactedSecureObjectError)
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnforceNetworkRulesForInternalStages(enforceNetworkRulesForInternalStages bool) *CurrentOrganizationAccountModel {
	c.EnforceNetworkRulesForInternalStages = tfconfig.BoolVariable(enforceNetworkRulesForInternalStages)
	return c
}

func (c *CurrentOrganizationAccountModel) WithErrorOnNondeterministicMerge(errorOnNondeterministicMerge bool) *CurrentOrganizationAccountModel {
	c.ErrorOnNondeterministicMerge = tfconfig.BoolVariable(errorOnNondeterministicMerge)
	return c
}

func (c *CurrentOrganizationAccountModel) WithErrorOnNondeterministicUpdate(errorOnNondeterministicUpdate bool) *CurrentOrganizationAccountModel {
	c.ErrorOnNondeterministicUpdate = tfconfig.BoolVariable(errorOnNondeterministicUpdate)
	return c
}

func (c *CurrentOrganizationAccountModel) WithEventTable(eventTable string) *CurrentOrganizationAccountModel {
	c.EventTable = tfconfig.StringVariable(eventTable)
	return c
}

func (c *CurrentOrganizationAccountModel) WithExternalOauthAddPrivilegedRolesToBlockedList(externalOauthAddPrivilegedRolesToBlockedList bool) *CurrentOrganizationAccountModel {
	c.ExternalOauthAddPrivilegedRolesToBlockedList = tfconfig.BoolVariable(externalOauthAddPrivilegedRolesToBlockedList)
	return c
}

func (c *CurrentOrganizationAccountModel) WithExternalVolume(externalVolume string) *CurrentOrganizationAccountModel {
	c.ExternalVolume = tfconfig.StringVariable(externalVolume)
	return c
}

func (c *CurrentOrganizationAccountModel) WithGeographyOutputFormat(geographyOutputFormat string) *CurrentOrganizationAccountModel {
	c.GeographyOutputFormat = tfconfig.StringVariable(geographyOutputFormat)
	return c
}

func (c *CurrentOrganizationAccountModel) WithGeometryOutputFormat(geometryOutputFormat string) *CurrentOrganizationAccountModel {
	c.GeometryOutputFormat = tfconfig.StringVariable(geometryOutputFormat)
	return c
}

func (c *CurrentOrganizationAccountModel) WithHybridTableLockTimeout(hybridTableLockTimeout int) *CurrentOrganizationAccountModel {
	c.HybridTableLockTimeout = tfconfig.IntegerVariable(hybridTableLockTimeout)
	return c
}

func (c *CurrentOrganizationAccountModel) WithInitialReplicationSizeLimitInTb(initialReplicationSizeLimitInTb string) *CurrentOrganizationAccountModel {
	c.InitialReplicationSizeLimitInTb = tfconfig.StringVariable(initialReplicationSizeLimitInTb)
	return c
}

func (c *CurrentOrganizationAccountModel) WithJdbcTreatDecimalAsInt(jdbcTreatDecimalAsInt bool) *CurrentOrganizationAccountModel {
	c.JdbcTreatDecimalAsInt = tfconfig.BoolVariable(jdbcTreatDecimalAsInt)
	return c
}

func (c *CurrentOrganizationAccountModel) WithJdbcTreatTimestampNtzAsUtc(jdbcTreatTimestampNtzAsUtc bool) *CurrentOrganizationAccountModel {
	c.JdbcTreatTimestampNtzAsUtc = tfconfig.BoolVariable(jdbcTreatTimestampNtzAsUtc)
	return c
}

func (c *CurrentOrganizationAccountModel) WithJdbcUseSessionTimezone(jdbcUseSessionTimezone bool) *CurrentOrganizationAccountModel {
	c.JdbcUseSessionTimezone = tfconfig.BoolVariable(jdbcUseSessionTimezone)
	return c
}

func (c *CurrentOrganizationAccountModel) WithJsTreatIntegerAsBigint(jsTreatIntegerAsBigint bool) *CurrentOrganizationAccountModel {
	c.JsTreatIntegerAsBigint = tfconfig.BoolVariable(jsTreatIntegerAsBigint)
	return c
}

func (c *CurrentOrganizationAccountModel) WithJsonIndent(jsonIndent int) *CurrentOrganizationAccountModel {
	c.JsonIndent = tfconfig.IntegerVariable(jsonIndent)
	return c
}

func (c *CurrentOrganizationAccountModel) WithListingAutoFulfillmentReplicationRefreshSchedule(listingAutoFulfillmentReplicationRefreshSchedule string) *CurrentOrganizationAccountModel {
	c.ListingAutoFulfillmentReplicationRefreshSchedule = tfconfig.StringVariable(listingAutoFulfillmentReplicationRefreshSchedule)
	return c
}

func (c *CurrentOrganizationAccountModel) WithLockTimeout(lockTimeout int) *CurrentOrganizationAccountModel {
	c.LockTimeout = tfconfig.IntegerVariable(lockTimeout)
	return c
}

func (c *CurrentOrganizationAccountModel) WithLogLevel(logLevel string) *CurrentOrganizationAccountModel {
	c.LogLevel = tfconfig.StringVariable(logLevel)
	return c
}

func (c *CurrentOrganizationAccountModel) WithMaxConcurrencyLevel(maxConcurrencyLevel int) *CurrentOrganizationAccountModel {
	c.MaxConcurrencyLevel = tfconfig.IntegerVariable(maxConcurrencyLevel)
	return c
}

func (c *CurrentOrganizationAccountModel) WithMaxDataExtensionTimeInDays(maxDataExtensionTimeInDays int) *CurrentOrganizationAccountModel {
	c.MaxDataExtensionTimeInDays = tfconfig.IntegerVariable(maxDataExtensionTimeInDays)
	return c
}

func (c *CurrentOrganizationAccountModel) WithMetricLevel(metricLevel string) *CurrentOrganizationAccountModel {
	c.MetricLevel = tfconfig.StringVariable(metricLevel)
	return c
}

func (c *CurrentOrganizationAccountModel) WithMinDataRetentionTimeInDays(minDataRetentionTimeInDays int) *CurrentOrganizationAccountModel {
	c.MinDataRetentionTimeInDays = tfconfig.IntegerVariable(minDataRetentionTimeInDays)
	return c
}

func (c *CurrentOrganizationAccountModel) WithMultiStatementCount(multiStatementCount int) *CurrentOrganizationAccountModel {
	c.MultiStatementCount = tfconfig.IntegerVariable(multiStatementCount)
	return c
}

func (c *CurrentOrganizationAccountModel) WithNetworkPolicy(networkPolicy string) *CurrentOrganizationAccountModel {
	c.NetworkPolicy = tfconfig.StringVariable(networkPolicy)
	return c
}

func (c *CurrentOrganizationAccountModel) WithNoorderSequenceAsDefault(noorderSequenceAsDefault bool) *CurrentOrganizationAccountModel {
	c.NoorderSequenceAsDefault = tfconfig.BoolVariable(noorderSequenceAsDefault)
	return c
}

func (c *CurrentOrganizationAccountModel) WithOauthAddPrivilegedRolesToBlockedList(oauthAddPrivilegedRolesToBlockedList bool) *CurrentOrganizationAccountModel {
	c.OauthAddPrivilegedRolesToBlockedList = tfconfig.BoolVariable(oauthAddPrivilegedRolesToBlockedList)
	return c
}

func (c *CurrentOrganizationAccountModel) WithOdbcTreatDecimalAsInt(odbcTreatDecimalAsInt bool) *CurrentOrganizationAccountModel {
	c.OdbcTreatDecimalAsInt = tfconfig.BoolVariable(odbcTreatDecimalAsInt)
	return c
}

func (c *CurrentOrganizationAccountModel) WithPasswordPolicy(passwordPolicy string) *CurrentOrganizationAccountModel {
	c.PasswordPolicy = tfconfig.StringVariable(passwordPolicy)
	return c
}

func (c *CurrentOrganizationAccountModel) WithPeriodicDataRekeying(periodicDataRekeying bool) *CurrentOrganizationAccountModel {
	c.PeriodicDataRekeying = tfconfig.BoolVariable(periodicDataRekeying)
	return c
}

func (c *CurrentOrganizationAccountModel) WithPipeExecutionPaused(pipeExecutionPaused bool) *CurrentOrganizationAccountModel {
	c.PipeExecutionPaused = tfconfig.BoolVariable(pipeExecutionPaused)
	return c
}

func (c *CurrentOrganizationAccountModel) WithPreventUnloadToInlineUrl(preventUnloadToInlineUrl bool) *CurrentOrganizationAccountModel {
	c.PreventUnloadToInlineUrl = tfconfig.BoolVariable(preventUnloadToInlineUrl)
	return c
}

func (c *CurrentOrganizationAccountModel) WithPreventUnloadToInternalStages(preventUnloadToInternalStages bool) *CurrentOrganizationAccountModel {
	c.PreventUnloadToInternalStages = tfconfig.BoolVariable(preventUnloadToInternalStages)
	return c
}

func (c *CurrentOrganizationAccountModel) WithPythonProfilerModules(pythonProfilerModules string) *CurrentOrganizationAccountModel {
	c.PythonProfilerModules = tfconfig.StringVariable(pythonProfilerModules)
	return c
}

func (c *CurrentOrganizationAccountModel) WithPythonProfilerTargetStage(pythonProfilerTargetStage string) *CurrentOrganizationAccountModel {
	c.PythonProfilerTargetStage = tfconfig.StringVariable(pythonProfilerTargetStage)
	return c
}

func (c *CurrentOrganizationAccountModel) WithQueryTag(queryTag string) *CurrentOrganizationAccountModel {
	c.QueryTag = tfconfig.StringVariable(queryTag)
	return c
}

func (c *CurrentOrganizationAccountModel) WithQuotedIdentifiersIgnoreCase(quotedIdentifiersIgnoreCase bool) *CurrentOrganizationAccountModel {
	c.QuotedIdentifiersIgnoreCase = tfconfig.BoolVariable(quotedIdentifiersIgnoreCase)
	return c
}

func (c *CurrentOrganizationAccountModel) WithReplaceInvalidCharacters(replaceInvalidCharacters bool) *CurrentOrganizationAccountModel {
	c.ReplaceInvalidCharacters = tfconfig.BoolVariable(replaceInvalidCharacters)
	return c
}

func (c *CurrentOrganizationAccountModel) WithRequireStorageIntegrationForStageCreation(requireStorageIntegrationForStageCreation bool) *CurrentOrganizationAccountModel {
	c.RequireStorageIntegrationForStageCreation = tfconfig.BoolVariable(requireStorageIntegrationForStageCreation)
	return c
}

func (c *CurrentOrganizationAccountModel) WithRequireStorageIntegrationForStageOperation(requireStorageIntegrationForStageOperation bool) *CurrentOrganizationAccountModel {
	c.RequireStorageIntegrationForStageOperation = tfconfig.BoolVariable(requireStorageIntegrationForStageOperation)
	return c
}

func (c *CurrentOrganizationAccountModel) WithResourceMonitor(resourceMonitor string) *CurrentOrganizationAccountModel {
	c.ResourceMonitor = tfconfig.StringVariable(resourceMonitor)
	return c
}

func (c *CurrentOrganizationAccountModel) WithRowsPerResultset(rowsPerResultset int) *CurrentOrganizationAccountModel {
	c.RowsPerResultset = tfconfig.IntegerVariable(rowsPerResultset)
	return c
}

func (c *CurrentOrganizationAccountModel) WithS3StageVpceDnsName(s3StageVpceDnsName string) *CurrentOrganizationAccountModel {
	c.S3StageVpceDnsName = tfconfig.StringVariable(s3StageVpceDnsName)
	return c
}

func (c *CurrentOrganizationAccountModel) WithSamlIdentityProvider(samlIdentityProvider string) *CurrentOrganizationAccountModel {
	c.SamlIdentityProvider = tfconfig.StringVariable(samlIdentityProvider)
	return c
}

func (c *CurrentOrganizationAccountModel) WithSearchPath(searchPath string) *CurrentOrganizationAccountModel {
	c.SearchPath = tfconfig.StringVariable(searchPath)
	return c
}

func (c *CurrentOrganizationAccountModel) WithServerlessTaskMaxStatementSize(serverlessTaskMaxStatementSize string) *CurrentOrganizationAccountModel {
	c.ServerlessTaskMaxStatementSize = tfconfig.StringVariable(serverlessTaskMaxStatementSize)
	return c
}

func (c *CurrentOrganizationAccountModel) WithServerlessTaskMinStatementSize(serverlessTaskMinStatementSize string) *CurrentOrganizationAccountModel {
	c.ServerlessTaskMinStatementSize = tfconfig.StringVariable(serverlessTaskMinStatementSize)
	return c
}

func (c *CurrentOrganizationAccountModel) WithSessionPolicy(sessionPolicy string) *CurrentOrganizationAccountModel {
	c.SessionPolicy = tfconfig.StringVariable(sessionPolicy)
	return c
}

func (c *CurrentOrganizationAccountModel) WithSimulatedDataSharingConsumer(simulatedDataSharingConsumer string) *CurrentOrganizationAccountModel {
	c.SimulatedDataSharingConsumer = tfconfig.StringVariable(simulatedDataSharingConsumer)
	return c
}

func (c *CurrentOrganizationAccountModel) WithSsoLoginPage(ssoLoginPage bool) *CurrentOrganizationAccountModel {
	c.SsoLoginPage = tfconfig.BoolVariable(ssoLoginPage)
	return c
}

func (c *CurrentOrganizationAccountModel) WithStatementQueuedTimeoutInSeconds(statementQueuedTimeoutInSeconds int) *CurrentOrganizationAccountModel {
	c.StatementQueuedTimeoutInSeconds = tfconfig.IntegerVariable(statementQueuedTimeoutInSeconds)
	return c
}

func (c *CurrentOrganizationAccountModel) WithStatementTimeoutInSeconds(statementTimeoutInSeconds int) *CurrentOrganizationAccountModel {
	c.StatementTimeoutInSeconds = tfconfig.IntegerVariable(statementTimeoutInSeconds)
	return c
}

func (c *CurrentOrganizationAccountModel) WithStorageSerializationPolicy(storageSerializationPolicy string) *CurrentOrganizationAccountModel {
	c.StorageSerializationPolicy = tfconfig.StringVariable(storageSerializationPolicy)
	return c
}

func (c *CurrentOrganizationAccountModel) WithStrictJsonOutput(strictJsonOutput bool) *CurrentOrganizationAccountModel {
	c.StrictJsonOutput = tfconfig.BoolVariable(strictJsonOutput)
	return c
}

func (c *CurrentOrganizationAccountModel) WithSuspendTaskAfterNumFailures(suspendTaskAfterNumFailures int) *CurrentOrganizationAccountModel {
	c.SuspendTaskAfterNumFailures = tfconfig.IntegerVariable(suspendTaskAfterNumFailures)
	return c
}

func (c *CurrentOrganizationAccountModel) WithTaskAutoRetryAttempts(taskAutoRetryAttempts int) *CurrentOrganizationAccountModel {
	c.TaskAutoRetryAttempts = tfconfig.IntegerVariable(taskAutoRetryAttempts)
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimeInputFormat(timeInputFormat string) *CurrentOrganizationAccountModel {
	c.TimeInputFormat = tfconfig.StringVariable(timeInputFormat)
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimeOutputFormat(timeOutputFormat string) *CurrentOrganizationAccountModel {
	c.TimeOutputFormat = tfconfig.StringVariable(timeOutputFormat)
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimestampDayIsAlways24h(timestampDayIsAlways24h bool) *CurrentOrganizationAccountModel {
	c.TimestampDayIsAlways24h = tfconfig.BoolVariable(timestampDayIsAlways24h)
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimestampInputFormat(timestampInputFormat string) *CurrentOrganizationAccountModel {
	c.TimestampInputFormat = tfconfig.StringVariable(timestampInputFormat)
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimestampLtzOutputFormat(timestampLtzOutputFormat string) *CurrentOrganizationAccountModel {
	c.TimestampLtzOutputFormat = tfconfig.StringVariable(timestampLtzOutputFormat)
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimestampNtzOutputFormat(timestampNtzOutputFormat string) *CurrentOrganizationAccountModel {
	c.TimestampNtzOutputFormat = tfconfig.StringVariable(timestampNtzOutputFormat)
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimestampOutputFormat(timestampOutputFormat string) *CurrentOrganizationAccountModel {
	c.TimestampOutputFormat = tfconfig.StringVariable(timestampOutputFormat)
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimestampTypeMapping(timestampTypeMapping string) *CurrentOrganizationAccountModel {
	c.TimestampTypeMapping = tfconfig.StringVariable(timestampTypeMapping)
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimestampTzOutputFormat(timestampTzOutputFormat string) *CurrentOrganizationAccountModel {
	c.TimestampTzOutputFormat = tfconfig.StringVariable(timestampTzOutputFormat)
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimezone(timezone string) *CurrentOrganizationAccountModel {
	c.Timezone = tfconfig.StringVariable(timezone)
	return c
}

func (c *CurrentOrganizationAccountModel) WithTraceLevel(traceLevel string) *CurrentOrganizationAccountModel {
	c.TraceLevel = tfconfig.StringVariable(traceLevel)
	return c
}

func (c *CurrentOrganizationAccountModel) WithTransactionAbortOnError(transactionAbortOnError bool) *CurrentOrganizationAccountModel {
	c.TransactionAbortOnError = tfconfig.BoolVariable(transactionAbortOnError)
	return c
}

func (c *CurrentOrganizationAccountModel) WithTransactionDefaultIsolationLevel(transactionDefaultIsolationLevel string) *CurrentOrganizationAccountModel {
	c.TransactionDefaultIsolationLevel = tfconfig.StringVariable(transactionDefaultIsolationLevel)
	return c
}

func (c *CurrentOrganizationAccountModel) WithTwoDigitCenturyStart(twoDigitCenturyStart int) *CurrentOrganizationAccountModel {
	c.TwoDigitCenturyStart = tfconfig.IntegerVariable(twoDigitCenturyStart)
	return c
}

func (c *CurrentOrganizationAccountModel) WithUnsupportedDdlAction(unsupportedDdlAction string) *CurrentOrganizationAccountModel {
	c.UnsupportedDdlAction = tfconfig.StringVariable(unsupportedDdlAction)
	return c
}

func (c *CurrentOrganizationAccountModel) WithUseCachedResult(useCachedResult bool) *CurrentOrganizationAccountModel {
	c.UseCachedResult = tfconfig.BoolVariable(useCachedResult)
	return c
}

func (c *CurrentOrganizationAccountModel) WithUserTaskManagedInitialWarehouseSize(userTaskManagedInitialWarehouseSize string) *CurrentOrganizationAccountModel {
	c.UserTaskManagedInitialWarehouseSize = tfconfig.StringVariable(userTaskManagedInitialWarehouseSize)
	return c
}

func (c *CurrentOrganizationAccountModel) WithUserTaskMinimumTriggerIntervalInSeconds(userTaskMinimumTriggerIntervalInSeconds int) *CurrentOrganizationAccountModel {
	c.UserTaskMinimumTriggerIntervalInSeconds = tfconfig.IntegerVariable(userTaskMinimumTriggerIntervalInSeconds)
	return c
}

func (c *CurrentOrganizationAccountModel) WithUserTaskTimeoutMs(userTaskTimeoutMs int) *CurrentOrganizationAccountModel {
	c.UserTaskTimeoutMs = tfconfig.IntegerVariable(userTaskTimeoutMs)
	return c
}

func (c *CurrentOrganizationAccountModel) WithWeekOfYearPolicy(weekOfYearPolicy int) *CurrentOrganizationAccountModel {
	c.WeekOfYearPolicy = tfconfig.IntegerVariable(weekOfYearPolicy)
	return c
}

func (c *CurrentOrganizationAccountModel) WithWeekStart(weekStart int) *CurrentOrganizationAccountModel {
	c.WeekStart = tfconfig.IntegerVariable(weekStart)
	return c
}

//////////////////////////////////////////
// below it's possible to set any value //
//////////////////////////////////////////

func (c *CurrentOrganizationAccountModel) WithAbortDetachedQueryValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.AbortDetachedQuery = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithActivePythonProfilerValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ActivePythonProfiler = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithAllowClientMfaCachingValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.AllowClientMfaCaching = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithAllowIdTokenValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.AllowIdToken = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithAutocommitValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.Autocommit = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithBaseLocationPrefixValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.BaseLocationPrefix = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithBinaryInputFormatValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.BinaryInputFormat = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithBinaryOutputFormatValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.BinaryOutputFormat = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithCatalogValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.Catalog = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithCatalogSyncValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.CatalogSync = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientEnableLogInfoStatementParametersValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ClientEnableLogInfoStatementParameters = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientEncryptionKeySizeValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ClientEncryptionKeySize = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientMemoryLimitValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ClientMemoryLimit = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientMetadataRequestUseConnectionCtxValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ClientMetadataRequestUseConnectionCtx = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientMetadataUseSessionDatabaseValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ClientMetadataUseSessionDatabase = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientPrefetchThreadsValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ClientPrefetchThreads = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientResultChunkSizeValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ClientResultChunkSize = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientResultColumnCaseInsensitiveValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ClientResultColumnCaseInsensitive = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientSessionKeepAliveValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ClientSessionKeepAlive = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientSessionKeepAliveHeartbeatFrequencyValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ClientSessionKeepAliveHeartbeatFrequency = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithClientTimestampTypeMappingValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ClientTimestampTypeMapping = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithCortexEnabledCrossRegionValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.CortexEnabledCrossRegion = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithCortexModelsAllowlistValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.CortexModelsAllowlist = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithCsvTimestampFormatValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.CsvTimestampFormat = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithDataRetentionTimeInDaysValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.DataRetentionTimeInDays = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithDateInputFormatValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.DateInputFormat = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithDateOutputFormatValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.DateOutputFormat = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithDefaultDdlCollationValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.DefaultDdlCollation = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithDefaultNotebookComputePoolCpuValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.DefaultNotebookComputePoolCpu = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithDefaultNotebookComputePoolGpuValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.DefaultNotebookComputePoolGpu = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithDefaultNullOrderingValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.DefaultNullOrdering = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithDefaultStreamlitNotebookWarehouseValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.DefaultStreamlitNotebookWarehouse = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithDisableUiDownloadButtonValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.DisableUiDownloadButton = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithDisableUserPrivilegeGrantsValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.DisableUserPrivilegeGrants = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableAutomaticSensitiveDataClassificationLogValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.EnableAutomaticSensitiveDataClassificationLog = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableEgressCostOptimizerValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.EnableEgressCostOptimizer = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableIdentifierFirstLoginValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.EnableIdentifierFirstLogin = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableInternalStagesPrivatelinkValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.EnableInternalStagesPrivatelink = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableTriSecretAndRekeyOptOutForImageRepositoryValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.EnableTriSecretAndRekeyOptOutForImageRepository = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableTriSecretAndRekeyOptOutForSpcsBlockStorageValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.EnableTriSecretAndRekeyOptOutForSpcsBlockStorage = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableUnhandledExceptionsReportingValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.EnableUnhandledExceptionsReporting = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableUnloadPhysicalTypeOptimizationValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.EnableUnloadPhysicalTypeOptimization = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableUnredactedQuerySyntaxErrorValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.EnableUnredactedQuerySyntaxError = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnableUnredactedSecureObjectErrorValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.EnableUnredactedSecureObjectError = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithEnforceNetworkRulesForInternalStagesValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.EnforceNetworkRulesForInternalStages = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithErrorOnNondeterministicMergeValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ErrorOnNondeterministicMerge = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithErrorOnNondeterministicUpdateValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ErrorOnNondeterministicUpdate = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithEventTableValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.EventTable = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithExternalOauthAddPrivilegedRolesToBlockedListValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ExternalOauthAddPrivilegedRolesToBlockedList = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithExternalVolumeValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ExternalVolume = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithGeographyOutputFormatValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.GeographyOutputFormat = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithGeometryOutputFormatValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.GeometryOutputFormat = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithHybridTableLockTimeoutValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.HybridTableLockTimeout = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithInitialReplicationSizeLimitInTbValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.InitialReplicationSizeLimitInTb = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithJdbcTreatDecimalAsIntValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.JdbcTreatDecimalAsInt = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithJdbcTreatTimestampNtzAsUtcValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.JdbcTreatTimestampNtzAsUtc = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithJdbcUseSessionTimezoneValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.JdbcUseSessionTimezone = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithJsTreatIntegerAsBigintValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.JsTreatIntegerAsBigint = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithJsonIndentValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.JsonIndent = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithListingAutoFulfillmentReplicationRefreshScheduleValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ListingAutoFulfillmentReplicationRefreshSchedule = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithLockTimeoutValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.LockTimeout = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithLogLevelValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.LogLevel = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithMaxConcurrencyLevelValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.MaxConcurrencyLevel = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithMaxDataExtensionTimeInDaysValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.MaxDataExtensionTimeInDays = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithMetricLevelValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.MetricLevel = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithMinDataRetentionTimeInDaysValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.MinDataRetentionTimeInDays = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithMultiStatementCountValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.MultiStatementCount = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithNetworkPolicyValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.NetworkPolicy = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithNoorderSequenceAsDefaultValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.NoorderSequenceAsDefault = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithOauthAddPrivilegedRolesToBlockedListValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.OauthAddPrivilegedRolesToBlockedList = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithOdbcTreatDecimalAsIntValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.OdbcTreatDecimalAsInt = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithPasswordPolicyValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.PasswordPolicy = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithPeriodicDataRekeyingValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.PeriodicDataRekeying = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithPipeExecutionPausedValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.PipeExecutionPaused = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithPreventUnloadToInlineUrlValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.PreventUnloadToInlineUrl = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithPreventUnloadToInternalStagesValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.PreventUnloadToInternalStages = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithPythonProfilerModulesValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.PythonProfilerModules = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithPythonProfilerTargetStageValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.PythonProfilerTargetStage = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithQueryTagValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.QueryTag = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithQuotedIdentifiersIgnoreCaseValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.QuotedIdentifiersIgnoreCase = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithReplaceInvalidCharactersValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ReplaceInvalidCharacters = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithRequireStorageIntegrationForStageCreationValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.RequireStorageIntegrationForStageCreation = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithRequireStorageIntegrationForStageOperationValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.RequireStorageIntegrationForStageOperation = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithResourceMonitorValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ResourceMonitor = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithRowsPerResultsetValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.RowsPerResultset = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithS3StageVpceDnsNameValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.S3StageVpceDnsName = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithSamlIdentityProviderValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.SamlIdentityProvider = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithSearchPathValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.SearchPath = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithServerlessTaskMaxStatementSizeValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ServerlessTaskMaxStatementSize = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithServerlessTaskMinStatementSizeValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.ServerlessTaskMinStatementSize = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithSessionPolicyValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.SessionPolicy = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithSimulatedDataSharingConsumerValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.SimulatedDataSharingConsumer = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithSsoLoginPageValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.SsoLoginPage = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithStatementQueuedTimeoutInSecondsValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.StatementQueuedTimeoutInSeconds = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithStatementTimeoutInSecondsValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.StatementTimeoutInSeconds = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithStorageSerializationPolicyValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.StorageSerializationPolicy = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithStrictJsonOutputValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.StrictJsonOutput = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithSuspendTaskAfterNumFailuresValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.SuspendTaskAfterNumFailures = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithTaskAutoRetryAttemptsValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.TaskAutoRetryAttempts = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimeInputFormatValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.TimeInputFormat = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimeOutputFormatValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.TimeOutputFormat = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimestampDayIsAlways24hValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.TimestampDayIsAlways24h = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimestampInputFormatValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.TimestampInputFormat = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimestampLtzOutputFormatValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.TimestampLtzOutputFormat = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimestampNtzOutputFormatValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.TimestampNtzOutputFormat = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimestampOutputFormatValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.TimestampOutputFormat = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimestampTypeMappingValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.TimestampTypeMapping = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimestampTzOutputFormatValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.TimestampTzOutputFormat = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithTimezoneValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.Timezone = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithTraceLevelValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.TraceLevel = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithTransactionAbortOnErrorValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.TransactionAbortOnError = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithTransactionDefaultIsolationLevelValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.TransactionDefaultIsolationLevel = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithTwoDigitCenturyStartValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.TwoDigitCenturyStart = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithUnsupportedDdlActionValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.UnsupportedDdlAction = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithUseCachedResultValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.UseCachedResult = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithUserTaskManagedInitialWarehouseSizeValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.UserTaskManagedInitialWarehouseSize = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithUserTaskMinimumTriggerIntervalInSecondsValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.UserTaskMinimumTriggerIntervalInSeconds = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithUserTaskTimeoutMsValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.UserTaskTimeoutMs = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithWeekOfYearPolicyValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.WeekOfYearPolicy = value
	return c
}

func (c *CurrentOrganizationAccountModel) WithWeekStartValue(value tfconfig.Variable) *CurrentOrganizationAccountModel {
	c.WeekStart = value
	return c
}
