// Code generated by config model builder generator; DO NOT EDIT.

package model

import (
	"encoding/json"

	tfconfig "github.com/hashicorp/terraform-plugin-testing/config"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/config"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/resources"
)

type CurrentAccountModel struct {
	AbortDetachedQuery                               tfconfig.Variable `json:"abort_detached_query,omitempty"`
	ActivePythonProfiler                             tfconfig.Variable `json:"active_python_profiler,omitempty"`
	AllowClientMfaCaching                            tfconfig.Variable `json:"allow_client_mfa_caching,omitempty"`
	AllowIdToken                                     tfconfig.Variable `json:"allow_id_token,omitempty"`
	AuthenticationPolicy                             tfconfig.Variable `json:"authentication_policy,omitempty"`
	Autocommit                                       tfconfig.Variable `json:"autocommit,omitempty"`
	BaseLocationPrefix                               tfconfig.Variable `json:"base_location_prefix,omitempty"`
	BinaryInputFormat                                tfconfig.Variable `json:"binary_input_format,omitempty"`
	BinaryOutputFormat                               tfconfig.Variable `json:"binary_output_format,omitempty"`
	Catalog                                          tfconfig.Variable `json:"catalog,omitempty"`
	CatalogSync                                      tfconfig.Variable `json:"catalog_sync,omitempty"`
	ClientEnableLogInfoStatementParameters           tfconfig.Variable `json:"client_enable_log_info_statement_parameters,omitempty"`
	ClientEncryptionKeySize                          tfconfig.Variable `json:"client_encryption_key_size,omitempty"`
	ClientMemoryLimit                                tfconfig.Variable `json:"client_memory_limit,omitempty"`
	ClientMetadataRequestUseConnectionCtx            tfconfig.Variable `json:"client_metadata_request_use_connection_ctx,omitempty"`
	ClientMetadataUseSessionDatabase                 tfconfig.Variable `json:"client_metadata_use_session_database,omitempty"`
	ClientPrefetchThreads                            tfconfig.Variable `json:"client_prefetch_threads,omitempty"`
	ClientResultChunkSize                            tfconfig.Variable `json:"client_result_chunk_size,omitempty"`
	ClientResultColumnCaseInsensitive                tfconfig.Variable `json:"client_result_column_case_insensitive,omitempty"`
	ClientSessionKeepAlive                           tfconfig.Variable `json:"client_session_keep_alive,omitempty"`
	ClientSessionKeepAliveHeartbeatFrequency         tfconfig.Variable `json:"client_session_keep_alive_heartbeat_frequency,omitempty"`
	ClientTimestampTypeMapping                       tfconfig.Variable `json:"client_timestamp_type_mapping,omitempty"`
	CortexEnabledCrossRegion                         tfconfig.Variable `json:"cortex_enabled_cross_region,omitempty"`
	CortexModelsAllowlist                            tfconfig.Variable `json:"cortex_models_allowlist,omitempty"`
	CsvTimestampFormat                               tfconfig.Variable `json:"csv_timestamp_format,omitempty"`
	DataRetentionTimeInDays                          tfconfig.Variable `json:"data_retention_time_in_days,omitempty"`
	DateInputFormat                                  tfconfig.Variable `json:"date_input_format,omitempty"`
	DateOutputFormat                                 tfconfig.Variable `json:"date_output_format,omitempty"`
	DefaultDdlCollation                              tfconfig.Variable `json:"default_ddl_collation,omitempty"`
	DefaultNotebookComputePoolCpu                    tfconfig.Variable `json:"default_notebook_compute_pool_cpu,omitempty"`
	DefaultNotebookComputePoolGpu                    tfconfig.Variable `json:"default_notebook_compute_pool_gpu,omitempty"`
	DefaultNullOrdering                              tfconfig.Variable `json:"default_null_ordering,omitempty"`
	DefaultStreamlitNotebookWarehouse                tfconfig.Variable `json:"default_streamlit_notebook_warehouse,omitempty"`
	DisableUiDownloadButton                          tfconfig.Variable `json:"disable_ui_download_button,omitempty"`
	DisableUserPrivilegeGrants                       tfconfig.Variable `json:"disable_user_privilege_grants,omitempty"`
	EnableAutomaticSensitiveDataClassificationLog    tfconfig.Variable `json:"enable_automatic_sensitive_data_classification_log,omitempty"`
	EnableEgressCostOptimizer                        tfconfig.Variable `json:"enable_egress_cost_optimizer,omitempty"`
	EnableIdentifierFirstLogin                       tfconfig.Variable `json:"enable_identifier_first_login,omitempty"`
	EnableInternalStagesPrivatelink                  tfconfig.Variable `json:"enable_internal_stages_privatelink,omitempty"`
	EnableTriSecretAndRekeyOptOutForImageRepository  tfconfig.Variable `json:"enable_tri_secret_and_rekey_opt_out_for_image_repository,omitempty"`
	EnableTriSecretAndRekeyOptOutForSpcsBlockStorage tfconfig.Variable `json:"enable_tri_secret_and_rekey_opt_out_for_spcs_block_storage,omitempty"`
	EnableUnhandledExceptionsReporting               tfconfig.Variable `json:"enable_unhandled_exceptions_reporting,omitempty"`
	EnableUnloadPhysicalTypeOptimization             tfconfig.Variable `json:"enable_unload_physical_type_optimization,omitempty"`
	EnableUnredactedQuerySyntaxError                 tfconfig.Variable `json:"enable_unredacted_query_syntax_error,omitempty"`
	EnableUnredactedSecureObjectError                tfconfig.Variable `json:"enable_unredacted_secure_object_error,omitempty"`
	EnforceNetworkRulesForInternalStages             tfconfig.Variable `json:"enforce_network_rules_for_internal_stages,omitempty"`
	ErrorOnNondeterministicMerge                     tfconfig.Variable `json:"error_on_nondeterministic_merge,omitempty"`
	ErrorOnNondeterministicUpdate                    tfconfig.Variable `json:"error_on_nondeterministic_update,omitempty"`
	EventTable                                       tfconfig.Variable `json:"event_table,omitempty"`
	ExternalOauthAddPrivilegedRolesToBlockedList     tfconfig.Variable `json:"external_oauth_add_privileged_roles_to_blocked_list,omitempty"`
	ExternalVolume                                   tfconfig.Variable `json:"external_volume,omitempty"`
	FeaturePolicy                                    tfconfig.Variable `json:"feature_policy,omitempty"`
	GeographyOutputFormat                            tfconfig.Variable `json:"geography_output_format,omitempty"`
	GeometryOutputFormat                             tfconfig.Variable `json:"geometry_output_format,omitempty"`
	HybridTableLockTimeout                           tfconfig.Variable `json:"hybrid_table_lock_timeout,omitempty"`
	InitialReplicationSizeLimitInTb                  tfconfig.Variable `json:"initial_replication_size_limit_in_tb,omitempty"`
	JdbcTreatDecimalAsInt                            tfconfig.Variable `json:"jdbc_treat_decimal_as_int,omitempty"`
	JdbcTreatTimestampNtzAsUtc                       tfconfig.Variable `json:"jdbc_treat_timestamp_ntz_as_utc,omitempty"`
	JdbcUseSessionTimezone                           tfconfig.Variable `json:"jdbc_use_session_timezone,omitempty"`
	JsTreatIntegerAsBigint                           tfconfig.Variable `json:"js_treat_integer_as_bigint,omitempty"`
	JsonIndent                                       tfconfig.Variable `json:"json_indent,omitempty"`
	ListingAutoFulfillmentReplicationRefreshSchedule tfconfig.Variable `json:"listing_auto_fulfillment_replication_refresh_schedule,omitempty"`
	LockTimeout                                      tfconfig.Variable `json:"lock_timeout,omitempty"`
	LogLevel                                         tfconfig.Variable `json:"log_level,omitempty"`
	MaxConcurrencyLevel                              tfconfig.Variable `json:"max_concurrency_level,omitempty"`
	MaxDataExtensionTimeInDays                       tfconfig.Variable `json:"max_data_extension_time_in_days,omitempty"`
	MetricLevel                                      tfconfig.Variable `json:"metric_level,omitempty"`
	MinDataRetentionTimeInDays                       tfconfig.Variable `json:"min_data_retention_time_in_days,omitempty"`
	MultiStatementCount                              tfconfig.Variable `json:"multi_statement_count,omitempty"`
	NetworkPolicy                                    tfconfig.Variable `json:"network_policy,omitempty"`
	NoorderSequenceAsDefault                         tfconfig.Variable `json:"noorder_sequence_as_default,omitempty"`
	OauthAddPrivilegedRolesToBlockedList             tfconfig.Variable `json:"oauth_add_privileged_roles_to_blocked_list,omitempty"`
	OdbcTreatDecimalAsInt                            tfconfig.Variable `json:"odbc_treat_decimal_as_int,omitempty"`
	PackagesPolicy                                   tfconfig.Variable `json:"packages_policy,omitempty"`
	PasswordPolicy                                   tfconfig.Variable `json:"password_policy,omitempty"`
	PeriodicDataRekeying                             tfconfig.Variable `json:"periodic_data_rekeying,omitempty"`
	PipeExecutionPaused                              tfconfig.Variable `json:"pipe_execution_paused,omitempty"`
	PreventUnloadToInlineUrl                         tfconfig.Variable `json:"prevent_unload_to_inline_url,omitempty"`
	PreventUnloadToInternalStages                    tfconfig.Variable `json:"prevent_unload_to_internal_stages,omitempty"`
	PythonProfilerModules                            tfconfig.Variable `json:"python_profiler_modules,omitempty"`
	PythonProfilerTargetStage                        tfconfig.Variable `json:"python_profiler_target_stage,omitempty"`
	QueryTag                                         tfconfig.Variable `json:"query_tag,omitempty"`
	QuotedIdentifiersIgnoreCase                      tfconfig.Variable `json:"quoted_identifiers_ignore_case,omitempty"`
	ReplaceInvalidCharacters                         tfconfig.Variable `json:"replace_invalid_characters,omitempty"`
	RequireStorageIntegrationForStageCreation        tfconfig.Variable `json:"require_storage_integration_for_stage_creation,omitempty"`
	RequireStorageIntegrationForStageOperation       tfconfig.Variable `json:"require_storage_integration_for_stage_operation,omitempty"`
	ResourceMonitor                                  tfconfig.Variable `json:"resource_monitor,omitempty"`
	RowsPerResultset                                 tfconfig.Variable `json:"rows_per_resultset,omitempty"`
	S3StageVpceDnsName                               tfconfig.Variable `json:"s3_stage_vpce_dns_name,omitempty"`
	SamlIdentityProvider                             tfconfig.Variable `json:"saml_identity_provider,omitempty"`
	SearchPath                                       tfconfig.Variable `json:"search_path,omitempty"`
	ServerlessTaskMaxStatementSize                   tfconfig.Variable `json:"serverless_task_max_statement_size,omitempty"`
	ServerlessTaskMinStatementSize                   tfconfig.Variable `json:"serverless_task_min_statement_size,omitempty"`
	SessionPolicy                                    tfconfig.Variable `json:"session_policy,omitempty"`
	SimulatedDataSharingConsumer                     tfconfig.Variable `json:"simulated_data_sharing_consumer,omitempty"`
	SsoLoginPage                                     tfconfig.Variable `json:"sso_login_page,omitempty"`
	StatementQueuedTimeoutInSeconds                  tfconfig.Variable `json:"statement_queued_timeout_in_seconds,omitempty"`
	StatementTimeoutInSeconds                        tfconfig.Variable `json:"statement_timeout_in_seconds,omitempty"`
	StorageSerializationPolicy                       tfconfig.Variable `json:"storage_serialization_policy,omitempty"`
	StrictJsonOutput                                 tfconfig.Variable `json:"strict_json_output,omitempty"`
	SuspendTaskAfterNumFailures                      tfconfig.Variable `json:"suspend_task_after_num_failures,omitempty"`
	TaskAutoRetryAttempts                            tfconfig.Variable `json:"task_auto_retry_attempts,omitempty"`
	TimeInputFormat                                  tfconfig.Variable `json:"time_input_format,omitempty"`
	TimeOutputFormat                                 tfconfig.Variable `json:"time_output_format,omitempty"`
	TimestampDayIsAlways24h                          tfconfig.Variable `json:"timestamp_day_is_always_24h,omitempty"`
	TimestampInputFormat                             tfconfig.Variable `json:"timestamp_input_format,omitempty"`
	TimestampLtzOutputFormat                         tfconfig.Variable `json:"timestamp_ltz_output_format,omitempty"`
	TimestampNtzOutputFormat                         tfconfig.Variable `json:"timestamp_ntz_output_format,omitempty"`
	TimestampOutputFormat                            tfconfig.Variable `json:"timestamp_output_format,omitempty"`
	TimestampTypeMapping                             tfconfig.Variable `json:"timestamp_type_mapping,omitempty"`
	TimestampTzOutputFormat                          tfconfig.Variable `json:"timestamp_tz_output_format,omitempty"`
	Timezone                                         tfconfig.Variable `json:"timezone,omitempty"`
	TraceLevel                                       tfconfig.Variable `json:"trace_level,omitempty"`
	TransactionAbortOnError                          tfconfig.Variable `json:"transaction_abort_on_error,omitempty"`
	TransactionDefaultIsolationLevel                 tfconfig.Variable `json:"transaction_default_isolation_level,omitempty"`
	TwoDigitCenturyStart                             tfconfig.Variable `json:"two_digit_century_start,omitempty"`
	UnsupportedDdlAction                             tfconfig.Variable `json:"unsupported_ddl_action,omitempty"`
	UseCachedResult                                  tfconfig.Variable `json:"use_cached_result,omitempty"`
	UserTaskManagedInitialWarehouseSize              tfconfig.Variable `json:"user_task_managed_initial_warehouse_size,omitempty"`
	UserTaskMinimumTriggerIntervalInSeconds          tfconfig.Variable `json:"user_task_minimum_trigger_interval_in_seconds,omitempty"`
	UserTaskTimeoutMs                                tfconfig.Variable `json:"user_task_timeout_ms,omitempty"`
	WeekOfYearPolicy                                 tfconfig.Variable `json:"week_of_year_policy,omitempty"`
	WeekStart                                        tfconfig.Variable `json:"week_start,omitempty"`

	DynamicBlock *config.DynamicBlock `json:"dynamic,omitempty"`

	*config.ResourceModelMeta
}

/////////////////////////////////////////////////
// Basic builders (resource name and required) //
/////////////////////////////////////////////////

func CurrentAccount(
	resourceName string,
) *CurrentAccountModel {
	c := &CurrentAccountModel{ResourceModelMeta: config.Meta(resourceName, resources.CurrentAccount)}
	return c
}

func CurrentAccountWithDefaultMeta() *CurrentAccountModel {
	c := &CurrentAccountModel{ResourceModelMeta: config.DefaultMeta(resources.CurrentAccount)}
	return c
}

///////////////////////////////////////////////////////////////////////
// set proper json marshalling, handle depends on and dynamic blocks //
///////////////////////////////////////////////////////////////////////

func (c *CurrentAccountModel) MarshalJSON() ([]byte, error) {
	type Alias CurrentAccountModel
	return json.Marshal(&struct {
		*Alias
		DependsOn []string `json:"depends_on,omitempty"`
	}{
		Alias:     (*Alias)(c),
		DependsOn: c.DependsOn(),
	})
}

func (c *CurrentAccountModel) WithDependsOn(values ...string) *CurrentAccountModel {
	c.SetDependsOn(values...)
	return c
}

func (c *CurrentAccountModel) WithDynamicBlock(dynamicBlock *config.DynamicBlock) *CurrentAccountModel {
	c.DynamicBlock = dynamicBlock
	return c
}

/////////////////////////////////
// below all the proper values //
/////////////////////////////////

func (c *CurrentAccountModel) WithAbortDetachedQuery(abortDetachedQuery bool) *CurrentAccountModel {
	c.AbortDetachedQuery = tfconfig.BoolVariable(abortDetachedQuery)
	return c
}

func (c *CurrentAccountModel) WithActivePythonProfiler(activePythonProfiler string) *CurrentAccountModel {
	c.ActivePythonProfiler = tfconfig.StringVariable(activePythonProfiler)
	return c
}

func (c *CurrentAccountModel) WithAllowClientMfaCaching(allowClientMfaCaching bool) *CurrentAccountModel {
	c.AllowClientMfaCaching = tfconfig.BoolVariable(allowClientMfaCaching)
	return c
}

func (c *CurrentAccountModel) WithAllowIdToken(allowIdToken bool) *CurrentAccountModel {
	c.AllowIdToken = tfconfig.BoolVariable(allowIdToken)
	return c
}

func (c *CurrentAccountModel) WithAuthenticationPolicy(authenticationPolicy string) *CurrentAccountModel {
	c.AuthenticationPolicy = tfconfig.StringVariable(authenticationPolicy)
	return c
}

func (c *CurrentAccountModel) WithAutocommit(autocommit bool) *CurrentAccountModel {
	c.Autocommit = tfconfig.BoolVariable(autocommit)
	return c
}

func (c *CurrentAccountModel) WithBaseLocationPrefix(baseLocationPrefix string) *CurrentAccountModel {
	c.BaseLocationPrefix = tfconfig.StringVariable(baseLocationPrefix)
	return c
}

func (c *CurrentAccountModel) WithBinaryInputFormat(binaryInputFormat string) *CurrentAccountModel {
	c.BinaryInputFormat = tfconfig.StringVariable(binaryInputFormat)
	return c
}

func (c *CurrentAccountModel) WithBinaryOutputFormat(binaryOutputFormat string) *CurrentAccountModel {
	c.BinaryOutputFormat = tfconfig.StringVariable(binaryOutputFormat)
	return c
}

func (c *CurrentAccountModel) WithCatalog(catalog string) *CurrentAccountModel {
	c.Catalog = tfconfig.StringVariable(catalog)
	return c
}

func (c *CurrentAccountModel) WithCatalogSync(catalogSync string) *CurrentAccountModel {
	c.CatalogSync = tfconfig.StringVariable(catalogSync)
	return c
}

func (c *CurrentAccountModel) WithClientEnableLogInfoStatementParameters(clientEnableLogInfoStatementParameters bool) *CurrentAccountModel {
	c.ClientEnableLogInfoStatementParameters = tfconfig.BoolVariable(clientEnableLogInfoStatementParameters)
	return c
}

func (c *CurrentAccountModel) WithClientEncryptionKeySize(clientEncryptionKeySize int) *CurrentAccountModel {
	c.ClientEncryptionKeySize = tfconfig.IntegerVariable(clientEncryptionKeySize)
	return c
}

func (c *CurrentAccountModel) WithClientMemoryLimit(clientMemoryLimit int) *CurrentAccountModel {
	c.ClientMemoryLimit = tfconfig.IntegerVariable(clientMemoryLimit)
	return c
}

func (c *CurrentAccountModel) WithClientMetadataRequestUseConnectionCtx(clientMetadataRequestUseConnectionCtx bool) *CurrentAccountModel {
	c.ClientMetadataRequestUseConnectionCtx = tfconfig.BoolVariable(clientMetadataRequestUseConnectionCtx)
	return c
}

func (c *CurrentAccountModel) WithClientMetadataUseSessionDatabase(clientMetadataUseSessionDatabase bool) *CurrentAccountModel {
	c.ClientMetadataUseSessionDatabase = tfconfig.BoolVariable(clientMetadataUseSessionDatabase)
	return c
}

func (c *CurrentAccountModel) WithClientPrefetchThreads(clientPrefetchThreads int) *CurrentAccountModel {
	c.ClientPrefetchThreads = tfconfig.IntegerVariable(clientPrefetchThreads)
	return c
}

func (c *CurrentAccountModel) WithClientResultChunkSize(clientResultChunkSize int) *CurrentAccountModel {
	c.ClientResultChunkSize = tfconfig.IntegerVariable(clientResultChunkSize)
	return c
}

func (c *CurrentAccountModel) WithClientResultColumnCaseInsensitive(clientResultColumnCaseInsensitive bool) *CurrentAccountModel {
	c.ClientResultColumnCaseInsensitive = tfconfig.BoolVariable(clientResultColumnCaseInsensitive)
	return c
}

func (c *CurrentAccountModel) WithClientSessionKeepAlive(clientSessionKeepAlive bool) *CurrentAccountModel {
	c.ClientSessionKeepAlive = tfconfig.BoolVariable(clientSessionKeepAlive)
	return c
}

func (c *CurrentAccountModel) WithClientSessionKeepAliveHeartbeatFrequency(clientSessionKeepAliveHeartbeatFrequency int) *CurrentAccountModel {
	c.ClientSessionKeepAliveHeartbeatFrequency = tfconfig.IntegerVariable(clientSessionKeepAliveHeartbeatFrequency)
	return c
}

func (c *CurrentAccountModel) WithClientTimestampTypeMapping(clientTimestampTypeMapping string) *CurrentAccountModel {
	c.ClientTimestampTypeMapping = tfconfig.StringVariable(clientTimestampTypeMapping)
	return c
}

func (c *CurrentAccountModel) WithCortexEnabledCrossRegion(cortexEnabledCrossRegion string) *CurrentAccountModel {
	c.CortexEnabledCrossRegion = tfconfig.StringVariable(cortexEnabledCrossRegion)
	return c
}

func (c *CurrentAccountModel) WithCortexModelsAllowlist(cortexModelsAllowlist string) *CurrentAccountModel {
	c.CortexModelsAllowlist = tfconfig.StringVariable(cortexModelsAllowlist)
	return c
}

func (c *CurrentAccountModel) WithCsvTimestampFormat(csvTimestampFormat string) *CurrentAccountModel {
	c.CsvTimestampFormat = tfconfig.StringVariable(csvTimestampFormat)
	return c
}

func (c *CurrentAccountModel) WithDataRetentionTimeInDays(dataRetentionTimeInDays int) *CurrentAccountModel {
	c.DataRetentionTimeInDays = tfconfig.IntegerVariable(dataRetentionTimeInDays)
	return c
}

func (c *CurrentAccountModel) WithDateInputFormat(dateInputFormat string) *CurrentAccountModel {
	c.DateInputFormat = tfconfig.StringVariable(dateInputFormat)
	return c
}

func (c *CurrentAccountModel) WithDateOutputFormat(dateOutputFormat string) *CurrentAccountModel {
	c.DateOutputFormat = tfconfig.StringVariable(dateOutputFormat)
	return c
}

func (c *CurrentAccountModel) WithDefaultDdlCollation(defaultDdlCollation string) *CurrentAccountModel {
	c.DefaultDdlCollation = tfconfig.StringVariable(defaultDdlCollation)
	return c
}

func (c *CurrentAccountModel) WithDefaultNotebookComputePoolCpu(defaultNotebookComputePoolCpu string) *CurrentAccountModel {
	c.DefaultNotebookComputePoolCpu = tfconfig.StringVariable(defaultNotebookComputePoolCpu)
	return c
}

func (c *CurrentAccountModel) WithDefaultNotebookComputePoolGpu(defaultNotebookComputePoolGpu string) *CurrentAccountModel {
	c.DefaultNotebookComputePoolGpu = tfconfig.StringVariable(defaultNotebookComputePoolGpu)
	return c
}

func (c *CurrentAccountModel) WithDefaultNullOrdering(defaultNullOrdering string) *CurrentAccountModel {
	c.DefaultNullOrdering = tfconfig.StringVariable(defaultNullOrdering)
	return c
}

func (c *CurrentAccountModel) WithDefaultStreamlitNotebookWarehouse(defaultStreamlitNotebookWarehouse string) *CurrentAccountModel {
	c.DefaultStreamlitNotebookWarehouse = tfconfig.StringVariable(defaultStreamlitNotebookWarehouse)
	return c
}

func (c *CurrentAccountModel) WithDisableUiDownloadButton(disableUiDownloadButton bool) *CurrentAccountModel {
	c.DisableUiDownloadButton = tfconfig.BoolVariable(disableUiDownloadButton)
	return c
}

func (c *CurrentAccountModel) WithDisableUserPrivilegeGrants(disableUserPrivilegeGrants bool) *CurrentAccountModel {
	c.DisableUserPrivilegeGrants = tfconfig.BoolVariable(disableUserPrivilegeGrants)
	return c
}

func (c *CurrentAccountModel) WithEnableAutomaticSensitiveDataClassificationLog(enableAutomaticSensitiveDataClassificationLog bool) *CurrentAccountModel {
	c.EnableAutomaticSensitiveDataClassificationLog = tfconfig.BoolVariable(enableAutomaticSensitiveDataClassificationLog)
	return c
}

func (c *CurrentAccountModel) WithEnableEgressCostOptimizer(enableEgressCostOptimizer bool) *CurrentAccountModel {
	c.EnableEgressCostOptimizer = tfconfig.BoolVariable(enableEgressCostOptimizer)
	return c
}

func (c *CurrentAccountModel) WithEnableIdentifierFirstLogin(enableIdentifierFirstLogin bool) *CurrentAccountModel {
	c.EnableIdentifierFirstLogin = tfconfig.BoolVariable(enableIdentifierFirstLogin)
	return c
}

func (c *CurrentAccountModel) WithEnableInternalStagesPrivatelink(enableInternalStagesPrivatelink bool) *CurrentAccountModel {
	c.EnableInternalStagesPrivatelink = tfconfig.BoolVariable(enableInternalStagesPrivatelink)
	return c
}

func (c *CurrentAccountModel) WithEnableTriSecretAndRekeyOptOutForImageRepository(enableTriSecretAndRekeyOptOutForImageRepository bool) *CurrentAccountModel {
	c.EnableTriSecretAndRekeyOptOutForImageRepository = tfconfig.BoolVariable(enableTriSecretAndRekeyOptOutForImageRepository)
	return c
}

func (c *CurrentAccountModel) WithEnableTriSecretAndRekeyOptOutForSpcsBlockStorage(enableTriSecretAndRekeyOptOutForSpcsBlockStorage bool) *CurrentAccountModel {
	c.EnableTriSecretAndRekeyOptOutForSpcsBlockStorage = tfconfig.BoolVariable(enableTriSecretAndRekeyOptOutForSpcsBlockStorage)
	return c
}

func (c *CurrentAccountModel) WithEnableUnhandledExceptionsReporting(enableUnhandledExceptionsReporting bool) *CurrentAccountModel {
	c.EnableUnhandledExceptionsReporting = tfconfig.BoolVariable(enableUnhandledExceptionsReporting)
	return c
}

func (c *CurrentAccountModel) WithEnableUnloadPhysicalTypeOptimization(enableUnloadPhysicalTypeOptimization bool) *CurrentAccountModel {
	c.EnableUnloadPhysicalTypeOptimization = tfconfig.BoolVariable(enableUnloadPhysicalTypeOptimization)
	return c
}

func (c *CurrentAccountModel) WithEnableUnredactedQuerySyntaxError(enableUnredactedQuerySyntaxError bool) *CurrentAccountModel {
	c.EnableUnredactedQuerySyntaxError = tfconfig.BoolVariable(enableUnredactedQuerySyntaxError)
	return c
}

func (c *CurrentAccountModel) WithEnableUnredactedSecureObjectError(enableUnredactedSecureObjectError bool) *CurrentAccountModel {
	c.EnableUnredactedSecureObjectError = tfconfig.BoolVariable(enableUnredactedSecureObjectError)
	return c
}

func (c *CurrentAccountModel) WithEnforceNetworkRulesForInternalStages(enforceNetworkRulesForInternalStages bool) *CurrentAccountModel {
	c.EnforceNetworkRulesForInternalStages = tfconfig.BoolVariable(enforceNetworkRulesForInternalStages)
	return c
}

func (c *CurrentAccountModel) WithErrorOnNondeterministicMerge(errorOnNondeterministicMerge bool) *CurrentAccountModel {
	c.ErrorOnNondeterministicMerge = tfconfig.BoolVariable(errorOnNondeterministicMerge)
	return c
}

func (c *CurrentAccountModel) WithErrorOnNondeterministicUpdate(errorOnNondeterministicUpdate bool) *CurrentAccountModel {
	c.ErrorOnNondeterministicUpdate = tfconfig.BoolVariable(errorOnNondeterministicUpdate)
	return c
}

func (c *CurrentAccountModel) WithEventTable(eventTable string) *CurrentAccountModel {
	c.EventTable = tfconfig.StringVariable(eventTable)
	return c
}

func (c *CurrentAccountModel) WithExternalOauthAddPrivilegedRolesToBlockedList(externalOauthAddPrivilegedRolesToBlockedList bool) *CurrentAccountModel {
	c.ExternalOauthAddPrivilegedRolesToBlockedList = tfconfig.BoolVariable(externalOauthAddPrivilegedRolesToBlockedList)
	return c
}

func (c *CurrentAccountModel) WithExternalVolume(externalVolume string) *CurrentAccountModel {
	c.ExternalVolume = tfconfig.StringVariable(externalVolume)
	return c
}

func (c *CurrentAccountModel) WithFeaturePolicy(featurePolicy string) *CurrentAccountModel {
	c.FeaturePolicy = tfconfig.StringVariable(featurePolicy)
	return c
}

func (c *CurrentAccountModel) WithGeographyOutputFormat(geographyOutputFormat string) *CurrentAccountModel {
	c.GeographyOutputFormat = tfconfig.StringVariable(geographyOutputFormat)
	return c
}

func (c *CurrentAccountModel) WithGeometryOutputFormat(geometryOutputFormat string) *CurrentAccountModel {
	c.GeometryOutputFormat = tfconfig.StringVariable(geometryOutputFormat)
	return c
}

func (c *CurrentAccountModel) WithHybridTableLockTimeout(hybridTableLockTimeout int) *CurrentAccountModel {
	c.HybridTableLockTimeout = tfconfig.IntegerVariable(hybridTableLockTimeout)
	return c
}

func (c *CurrentAccountModel) WithInitialReplicationSizeLimitInTb(initialReplicationSizeLimitInTb string) *CurrentAccountModel {
	c.InitialReplicationSizeLimitInTb = tfconfig.StringVariable(initialReplicationSizeLimitInTb)
	return c
}

func (c *CurrentAccountModel) WithJdbcTreatDecimalAsInt(jdbcTreatDecimalAsInt bool) *CurrentAccountModel {
	c.JdbcTreatDecimalAsInt = tfconfig.BoolVariable(jdbcTreatDecimalAsInt)
	return c
}

func (c *CurrentAccountModel) WithJdbcTreatTimestampNtzAsUtc(jdbcTreatTimestampNtzAsUtc bool) *CurrentAccountModel {
	c.JdbcTreatTimestampNtzAsUtc = tfconfig.BoolVariable(jdbcTreatTimestampNtzAsUtc)
	return c
}

func (c *CurrentAccountModel) WithJdbcUseSessionTimezone(jdbcUseSessionTimezone bool) *CurrentAccountModel {
	c.JdbcUseSessionTimezone = tfconfig.BoolVariable(jdbcUseSessionTimezone)
	return c
}

func (c *CurrentAccountModel) WithJsTreatIntegerAsBigint(jsTreatIntegerAsBigint bool) *CurrentAccountModel {
	c.JsTreatIntegerAsBigint = tfconfig.BoolVariable(jsTreatIntegerAsBigint)
	return c
}

func (c *CurrentAccountModel) WithJsonIndent(jsonIndent int) *CurrentAccountModel {
	c.JsonIndent = tfconfig.IntegerVariable(jsonIndent)
	return c
}

func (c *CurrentAccountModel) WithListingAutoFulfillmentReplicationRefreshSchedule(listingAutoFulfillmentReplicationRefreshSchedule string) *CurrentAccountModel {
	c.ListingAutoFulfillmentReplicationRefreshSchedule = tfconfig.StringVariable(listingAutoFulfillmentReplicationRefreshSchedule)
	return c
}

func (c *CurrentAccountModel) WithLockTimeout(lockTimeout int) *CurrentAccountModel {
	c.LockTimeout = tfconfig.IntegerVariable(lockTimeout)
	return c
}

func (c *CurrentAccountModel) WithLogLevel(logLevel string) *CurrentAccountModel {
	c.LogLevel = tfconfig.StringVariable(logLevel)
	return c
}

func (c *CurrentAccountModel) WithMaxConcurrencyLevel(maxConcurrencyLevel int) *CurrentAccountModel {
	c.MaxConcurrencyLevel = tfconfig.IntegerVariable(maxConcurrencyLevel)
	return c
}

func (c *CurrentAccountModel) WithMaxDataExtensionTimeInDays(maxDataExtensionTimeInDays int) *CurrentAccountModel {
	c.MaxDataExtensionTimeInDays = tfconfig.IntegerVariable(maxDataExtensionTimeInDays)
	return c
}

func (c *CurrentAccountModel) WithMetricLevel(metricLevel string) *CurrentAccountModel {
	c.MetricLevel = tfconfig.StringVariable(metricLevel)
	return c
}

func (c *CurrentAccountModel) WithMinDataRetentionTimeInDays(minDataRetentionTimeInDays int) *CurrentAccountModel {
	c.MinDataRetentionTimeInDays = tfconfig.IntegerVariable(minDataRetentionTimeInDays)
	return c
}

func (c *CurrentAccountModel) WithMultiStatementCount(multiStatementCount int) *CurrentAccountModel {
	c.MultiStatementCount = tfconfig.IntegerVariable(multiStatementCount)
	return c
}

func (c *CurrentAccountModel) WithNetworkPolicy(networkPolicy string) *CurrentAccountModel {
	c.NetworkPolicy = tfconfig.StringVariable(networkPolicy)
	return c
}

func (c *CurrentAccountModel) WithNoorderSequenceAsDefault(noorderSequenceAsDefault bool) *CurrentAccountModel {
	c.NoorderSequenceAsDefault = tfconfig.BoolVariable(noorderSequenceAsDefault)
	return c
}

func (c *CurrentAccountModel) WithOauthAddPrivilegedRolesToBlockedList(oauthAddPrivilegedRolesToBlockedList bool) *CurrentAccountModel {
	c.OauthAddPrivilegedRolesToBlockedList = tfconfig.BoolVariable(oauthAddPrivilegedRolesToBlockedList)
	return c
}

func (c *CurrentAccountModel) WithOdbcTreatDecimalAsInt(odbcTreatDecimalAsInt bool) *CurrentAccountModel {
	c.OdbcTreatDecimalAsInt = tfconfig.BoolVariable(odbcTreatDecimalAsInt)
	return c
}

func (c *CurrentAccountModel) WithPackagesPolicy(packagesPolicy string) *CurrentAccountModel {
	c.PackagesPolicy = tfconfig.StringVariable(packagesPolicy)
	return c
}

func (c *CurrentAccountModel) WithPasswordPolicy(passwordPolicy string) *CurrentAccountModel {
	c.PasswordPolicy = tfconfig.StringVariable(passwordPolicy)
	return c
}

func (c *CurrentAccountModel) WithPeriodicDataRekeying(periodicDataRekeying bool) *CurrentAccountModel {
	c.PeriodicDataRekeying = tfconfig.BoolVariable(periodicDataRekeying)
	return c
}

func (c *CurrentAccountModel) WithPipeExecutionPaused(pipeExecutionPaused bool) *CurrentAccountModel {
	c.PipeExecutionPaused = tfconfig.BoolVariable(pipeExecutionPaused)
	return c
}

func (c *CurrentAccountModel) WithPreventUnloadToInlineUrl(preventUnloadToInlineUrl bool) *CurrentAccountModel {
	c.PreventUnloadToInlineUrl = tfconfig.BoolVariable(preventUnloadToInlineUrl)
	return c
}

func (c *CurrentAccountModel) WithPreventUnloadToInternalStages(preventUnloadToInternalStages bool) *CurrentAccountModel {
	c.PreventUnloadToInternalStages = tfconfig.BoolVariable(preventUnloadToInternalStages)
	return c
}

func (c *CurrentAccountModel) WithPythonProfilerModules(pythonProfilerModules string) *CurrentAccountModel {
	c.PythonProfilerModules = tfconfig.StringVariable(pythonProfilerModules)
	return c
}

func (c *CurrentAccountModel) WithPythonProfilerTargetStage(pythonProfilerTargetStage string) *CurrentAccountModel {
	c.PythonProfilerTargetStage = tfconfig.StringVariable(pythonProfilerTargetStage)
	return c
}

func (c *CurrentAccountModel) WithQueryTag(queryTag string) *CurrentAccountModel {
	c.QueryTag = tfconfig.StringVariable(queryTag)
	return c
}

func (c *CurrentAccountModel) WithQuotedIdentifiersIgnoreCase(quotedIdentifiersIgnoreCase bool) *CurrentAccountModel {
	c.QuotedIdentifiersIgnoreCase = tfconfig.BoolVariable(quotedIdentifiersIgnoreCase)
	return c
}

func (c *CurrentAccountModel) WithReplaceInvalidCharacters(replaceInvalidCharacters bool) *CurrentAccountModel {
	c.ReplaceInvalidCharacters = tfconfig.BoolVariable(replaceInvalidCharacters)
	return c
}

func (c *CurrentAccountModel) WithRequireStorageIntegrationForStageCreation(requireStorageIntegrationForStageCreation bool) *CurrentAccountModel {
	c.RequireStorageIntegrationForStageCreation = tfconfig.BoolVariable(requireStorageIntegrationForStageCreation)
	return c
}

func (c *CurrentAccountModel) WithRequireStorageIntegrationForStageOperation(requireStorageIntegrationForStageOperation bool) *CurrentAccountModel {
	c.RequireStorageIntegrationForStageOperation = tfconfig.BoolVariable(requireStorageIntegrationForStageOperation)
	return c
}

func (c *CurrentAccountModel) WithResourceMonitor(resourceMonitor string) *CurrentAccountModel {
	c.ResourceMonitor = tfconfig.StringVariable(resourceMonitor)
	return c
}

func (c *CurrentAccountModel) WithRowsPerResultset(rowsPerResultset int) *CurrentAccountModel {
	c.RowsPerResultset = tfconfig.IntegerVariable(rowsPerResultset)
	return c
}

func (c *CurrentAccountModel) WithS3StageVpceDnsName(s3StageVpceDnsName string) *CurrentAccountModel {
	c.S3StageVpceDnsName = tfconfig.StringVariable(s3StageVpceDnsName)
	return c
}

func (c *CurrentAccountModel) WithSamlIdentityProvider(samlIdentityProvider string) *CurrentAccountModel {
	c.SamlIdentityProvider = tfconfig.StringVariable(samlIdentityProvider)
	return c
}

func (c *CurrentAccountModel) WithSearchPath(searchPath string) *CurrentAccountModel {
	c.SearchPath = tfconfig.StringVariable(searchPath)
	return c
}

func (c *CurrentAccountModel) WithServerlessTaskMaxStatementSize(serverlessTaskMaxStatementSize string) *CurrentAccountModel {
	c.ServerlessTaskMaxStatementSize = tfconfig.StringVariable(serverlessTaskMaxStatementSize)
	return c
}

func (c *CurrentAccountModel) WithServerlessTaskMinStatementSize(serverlessTaskMinStatementSize string) *CurrentAccountModel {
	c.ServerlessTaskMinStatementSize = tfconfig.StringVariable(serverlessTaskMinStatementSize)
	return c
}

func (c *CurrentAccountModel) WithSessionPolicy(sessionPolicy string) *CurrentAccountModel {
	c.SessionPolicy = tfconfig.StringVariable(sessionPolicy)
	return c
}

func (c *CurrentAccountModel) WithSimulatedDataSharingConsumer(simulatedDataSharingConsumer string) *CurrentAccountModel {
	c.SimulatedDataSharingConsumer = tfconfig.StringVariable(simulatedDataSharingConsumer)
	return c
}

func (c *CurrentAccountModel) WithSsoLoginPage(ssoLoginPage bool) *CurrentAccountModel {
	c.SsoLoginPage = tfconfig.BoolVariable(ssoLoginPage)
	return c
}

func (c *CurrentAccountModel) WithStatementQueuedTimeoutInSeconds(statementQueuedTimeoutInSeconds int) *CurrentAccountModel {
	c.StatementQueuedTimeoutInSeconds = tfconfig.IntegerVariable(statementQueuedTimeoutInSeconds)
	return c
}

func (c *CurrentAccountModel) WithStatementTimeoutInSeconds(statementTimeoutInSeconds int) *CurrentAccountModel {
	c.StatementTimeoutInSeconds = tfconfig.IntegerVariable(statementTimeoutInSeconds)
	return c
}

func (c *CurrentAccountModel) WithStorageSerializationPolicy(storageSerializationPolicy string) *CurrentAccountModel {
	c.StorageSerializationPolicy = tfconfig.StringVariable(storageSerializationPolicy)
	return c
}

func (c *CurrentAccountModel) WithStrictJsonOutput(strictJsonOutput bool) *CurrentAccountModel {
	c.StrictJsonOutput = tfconfig.BoolVariable(strictJsonOutput)
	return c
}

func (c *CurrentAccountModel) WithSuspendTaskAfterNumFailures(suspendTaskAfterNumFailures int) *CurrentAccountModel {
	c.SuspendTaskAfterNumFailures = tfconfig.IntegerVariable(suspendTaskAfterNumFailures)
	return c
}

func (c *CurrentAccountModel) WithTaskAutoRetryAttempts(taskAutoRetryAttempts int) *CurrentAccountModel {
	c.TaskAutoRetryAttempts = tfconfig.IntegerVariable(taskAutoRetryAttempts)
	return c
}

func (c *CurrentAccountModel) WithTimeInputFormat(timeInputFormat string) *CurrentAccountModel {
	c.TimeInputFormat = tfconfig.StringVariable(timeInputFormat)
	return c
}

func (c *CurrentAccountModel) WithTimeOutputFormat(timeOutputFormat string) *CurrentAccountModel {
	c.TimeOutputFormat = tfconfig.StringVariable(timeOutputFormat)
	return c
}

func (c *CurrentAccountModel) WithTimestampDayIsAlways24h(timestampDayIsAlways24h bool) *CurrentAccountModel {
	c.TimestampDayIsAlways24h = tfconfig.BoolVariable(timestampDayIsAlways24h)
	return c
}

func (c *CurrentAccountModel) WithTimestampInputFormat(timestampInputFormat string) *CurrentAccountModel {
	c.TimestampInputFormat = tfconfig.StringVariable(timestampInputFormat)
	return c
}

func (c *CurrentAccountModel) WithTimestampLtzOutputFormat(timestampLtzOutputFormat string) *CurrentAccountModel {
	c.TimestampLtzOutputFormat = tfconfig.StringVariable(timestampLtzOutputFormat)
	return c
}

func (c *CurrentAccountModel) WithTimestampNtzOutputFormat(timestampNtzOutputFormat string) *CurrentAccountModel {
	c.TimestampNtzOutputFormat = tfconfig.StringVariable(timestampNtzOutputFormat)
	return c
}

func (c *CurrentAccountModel) WithTimestampOutputFormat(timestampOutputFormat string) *CurrentAccountModel {
	c.TimestampOutputFormat = tfconfig.StringVariable(timestampOutputFormat)
	return c
}

func (c *CurrentAccountModel) WithTimestampTypeMapping(timestampTypeMapping string) *CurrentAccountModel {
	c.TimestampTypeMapping = tfconfig.StringVariable(timestampTypeMapping)
	return c
}

func (c *CurrentAccountModel) WithTimestampTzOutputFormat(timestampTzOutputFormat string) *CurrentAccountModel {
	c.TimestampTzOutputFormat = tfconfig.StringVariable(timestampTzOutputFormat)
	return c
}

func (c *CurrentAccountModel) WithTimezone(timezone string) *CurrentAccountModel {
	c.Timezone = tfconfig.StringVariable(timezone)
	return c
}

func (c *CurrentAccountModel) WithTraceLevel(traceLevel string) *CurrentAccountModel {
	c.TraceLevel = tfconfig.StringVariable(traceLevel)
	return c
}

func (c *CurrentAccountModel) WithTransactionAbortOnError(transactionAbortOnError bool) *CurrentAccountModel {
	c.TransactionAbortOnError = tfconfig.BoolVariable(transactionAbortOnError)
	return c
}

func (c *CurrentAccountModel) WithTransactionDefaultIsolationLevel(transactionDefaultIsolationLevel string) *CurrentAccountModel {
	c.TransactionDefaultIsolationLevel = tfconfig.StringVariable(transactionDefaultIsolationLevel)
	return c
}

func (c *CurrentAccountModel) WithTwoDigitCenturyStart(twoDigitCenturyStart int) *CurrentAccountModel {
	c.TwoDigitCenturyStart = tfconfig.IntegerVariable(twoDigitCenturyStart)
	return c
}

func (c *CurrentAccountModel) WithUnsupportedDdlAction(unsupportedDdlAction string) *CurrentAccountModel {
	c.UnsupportedDdlAction = tfconfig.StringVariable(unsupportedDdlAction)
	return c
}

func (c *CurrentAccountModel) WithUseCachedResult(useCachedResult bool) *CurrentAccountModel {
	c.UseCachedResult = tfconfig.BoolVariable(useCachedResult)
	return c
}

func (c *CurrentAccountModel) WithUserTaskManagedInitialWarehouseSize(userTaskManagedInitialWarehouseSize string) *CurrentAccountModel {
	c.UserTaskManagedInitialWarehouseSize = tfconfig.StringVariable(userTaskManagedInitialWarehouseSize)
	return c
}

func (c *CurrentAccountModel) WithUserTaskMinimumTriggerIntervalInSeconds(userTaskMinimumTriggerIntervalInSeconds int) *CurrentAccountModel {
	c.UserTaskMinimumTriggerIntervalInSeconds = tfconfig.IntegerVariable(userTaskMinimumTriggerIntervalInSeconds)
	return c
}

func (c *CurrentAccountModel) WithUserTaskTimeoutMs(userTaskTimeoutMs int) *CurrentAccountModel {
	c.UserTaskTimeoutMs = tfconfig.IntegerVariable(userTaskTimeoutMs)
	return c
}

func (c *CurrentAccountModel) WithWeekOfYearPolicy(weekOfYearPolicy int) *CurrentAccountModel {
	c.WeekOfYearPolicy = tfconfig.IntegerVariable(weekOfYearPolicy)
	return c
}

func (c *CurrentAccountModel) WithWeekStart(weekStart int) *CurrentAccountModel {
	c.WeekStart = tfconfig.IntegerVariable(weekStart)
	return c
}

//////////////////////////////////////////
// below it's possible to set any value //
//////////////////////////////////////////

func (c *CurrentAccountModel) WithAbortDetachedQueryValue(value tfconfig.Variable) *CurrentAccountModel {
	c.AbortDetachedQuery = value
	return c
}

func (c *CurrentAccountModel) WithActivePythonProfilerValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ActivePythonProfiler = value
	return c
}

func (c *CurrentAccountModel) WithAllowClientMfaCachingValue(value tfconfig.Variable) *CurrentAccountModel {
	c.AllowClientMfaCaching = value
	return c
}

func (c *CurrentAccountModel) WithAllowIdTokenValue(value tfconfig.Variable) *CurrentAccountModel {
	c.AllowIdToken = value
	return c
}

func (c *CurrentAccountModel) WithAuthenticationPolicyValue(value tfconfig.Variable) *CurrentAccountModel {
	c.AuthenticationPolicy = value
	return c
}

func (c *CurrentAccountModel) WithAutocommitValue(value tfconfig.Variable) *CurrentAccountModel {
	c.Autocommit = value
	return c
}

func (c *CurrentAccountModel) WithBaseLocationPrefixValue(value tfconfig.Variable) *CurrentAccountModel {
	c.BaseLocationPrefix = value
	return c
}

func (c *CurrentAccountModel) WithBinaryInputFormatValue(value tfconfig.Variable) *CurrentAccountModel {
	c.BinaryInputFormat = value
	return c
}

func (c *CurrentAccountModel) WithBinaryOutputFormatValue(value tfconfig.Variable) *CurrentAccountModel {
	c.BinaryOutputFormat = value
	return c
}

func (c *CurrentAccountModel) WithCatalogValue(value tfconfig.Variable) *CurrentAccountModel {
	c.Catalog = value
	return c
}

func (c *CurrentAccountModel) WithCatalogSyncValue(value tfconfig.Variable) *CurrentAccountModel {
	c.CatalogSync = value
	return c
}

func (c *CurrentAccountModel) WithClientEnableLogInfoStatementParametersValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ClientEnableLogInfoStatementParameters = value
	return c
}

func (c *CurrentAccountModel) WithClientEncryptionKeySizeValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ClientEncryptionKeySize = value
	return c
}

func (c *CurrentAccountModel) WithClientMemoryLimitValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ClientMemoryLimit = value
	return c
}

func (c *CurrentAccountModel) WithClientMetadataRequestUseConnectionCtxValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ClientMetadataRequestUseConnectionCtx = value
	return c
}

func (c *CurrentAccountModel) WithClientMetadataUseSessionDatabaseValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ClientMetadataUseSessionDatabase = value
	return c
}

func (c *CurrentAccountModel) WithClientPrefetchThreadsValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ClientPrefetchThreads = value
	return c
}

func (c *CurrentAccountModel) WithClientResultChunkSizeValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ClientResultChunkSize = value
	return c
}

func (c *CurrentAccountModel) WithClientResultColumnCaseInsensitiveValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ClientResultColumnCaseInsensitive = value
	return c
}

func (c *CurrentAccountModel) WithClientSessionKeepAliveValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ClientSessionKeepAlive = value
	return c
}

func (c *CurrentAccountModel) WithClientSessionKeepAliveHeartbeatFrequencyValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ClientSessionKeepAliveHeartbeatFrequency = value
	return c
}

func (c *CurrentAccountModel) WithClientTimestampTypeMappingValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ClientTimestampTypeMapping = value
	return c
}

func (c *CurrentAccountModel) WithCortexEnabledCrossRegionValue(value tfconfig.Variable) *CurrentAccountModel {
	c.CortexEnabledCrossRegion = value
	return c
}

func (c *CurrentAccountModel) WithCortexModelsAllowlistValue(value tfconfig.Variable) *CurrentAccountModel {
	c.CortexModelsAllowlist = value
	return c
}

func (c *CurrentAccountModel) WithCsvTimestampFormatValue(value tfconfig.Variable) *CurrentAccountModel {
	c.CsvTimestampFormat = value
	return c
}

func (c *CurrentAccountModel) WithDataRetentionTimeInDaysValue(value tfconfig.Variable) *CurrentAccountModel {
	c.DataRetentionTimeInDays = value
	return c
}

func (c *CurrentAccountModel) WithDateInputFormatValue(value tfconfig.Variable) *CurrentAccountModel {
	c.DateInputFormat = value
	return c
}

func (c *CurrentAccountModel) WithDateOutputFormatValue(value tfconfig.Variable) *CurrentAccountModel {
	c.DateOutputFormat = value
	return c
}

func (c *CurrentAccountModel) WithDefaultDdlCollationValue(value tfconfig.Variable) *CurrentAccountModel {
	c.DefaultDdlCollation = value
	return c
}

func (c *CurrentAccountModel) WithDefaultNotebookComputePoolCpuValue(value tfconfig.Variable) *CurrentAccountModel {
	c.DefaultNotebookComputePoolCpu = value
	return c
}

func (c *CurrentAccountModel) WithDefaultNotebookComputePoolGpuValue(value tfconfig.Variable) *CurrentAccountModel {
	c.DefaultNotebookComputePoolGpu = value
	return c
}

func (c *CurrentAccountModel) WithDefaultNullOrderingValue(value tfconfig.Variable) *CurrentAccountModel {
	c.DefaultNullOrdering = value
	return c
}

func (c *CurrentAccountModel) WithDefaultStreamlitNotebookWarehouseValue(value tfconfig.Variable) *CurrentAccountModel {
	c.DefaultStreamlitNotebookWarehouse = value
	return c
}

func (c *CurrentAccountModel) WithDisableUiDownloadButtonValue(value tfconfig.Variable) *CurrentAccountModel {
	c.DisableUiDownloadButton = value
	return c
}

func (c *CurrentAccountModel) WithDisableUserPrivilegeGrantsValue(value tfconfig.Variable) *CurrentAccountModel {
	c.DisableUserPrivilegeGrants = value
	return c
}

func (c *CurrentAccountModel) WithEnableAutomaticSensitiveDataClassificationLogValue(value tfconfig.Variable) *CurrentAccountModel {
	c.EnableAutomaticSensitiveDataClassificationLog = value
	return c
}

func (c *CurrentAccountModel) WithEnableEgressCostOptimizerValue(value tfconfig.Variable) *CurrentAccountModel {
	c.EnableEgressCostOptimizer = value
	return c
}

func (c *CurrentAccountModel) WithEnableIdentifierFirstLoginValue(value tfconfig.Variable) *CurrentAccountModel {
	c.EnableIdentifierFirstLogin = value
	return c
}

func (c *CurrentAccountModel) WithEnableInternalStagesPrivatelinkValue(value tfconfig.Variable) *CurrentAccountModel {
	c.EnableInternalStagesPrivatelink = value
	return c
}

func (c *CurrentAccountModel) WithEnableTriSecretAndRekeyOptOutForImageRepositoryValue(value tfconfig.Variable) *CurrentAccountModel {
	c.EnableTriSecretAndRekeyOptOutForImageRepository = value
	return c
}

func (c *CurrentAccountModel) WithEnableTriSecretAndRekeyOptOutForSpcsBlockStorageValue(value tfconfig.Variable) *CurrentAccountModel {
	c.EnableTriSecretAndRekeyOptOutForSpcsBlockStorage = value
	return c
}

func (c *CurrentAccountModel) WithEnableUnhandledExceptionsReportingValue(value tfconfig.Variable) *CurrentAccountModel {
	c.EnableUnhandledExceptionsReporting = value
	return c
}

func (c *CurrentAccountModel) WithEnableUnloadPhysicalTypeOptimizationValue(value tfconfig.Variable) *CurrentAccountModel {
	c.EnableUnloadPhysicalTypeOptimization = value
	return c
}

func (c *CurrentAccountModel) WithEnableUnredactedQuerySyntaxErrorValue(value tfconfig.Variable) *CurrentAccountModel {
	c.EnableUnredactedQuerySyntaxError = value
	return c
}

func (c *CurrentAccountModel) WithEnableUnredactedSecureObjectErrorValue(value tfconfig.Variable) *CurrentAccountModel {
	c.EnableUnredactedSecureObjectError = value
	return c
}

func (c *CurrentAccountModel) WithEnforceNetworkRulesForInternalStagesValue(value tfconfig.Variable) *CurrentAccountModel {
	c.EnforceNetworkRulesForInternalStages = value
	return c
}

func (c *CurrentAccountModel) WithErrorOnNondeterministicMergeValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ErrorOnNondeterministicMerge = value
	return c
}

func (c *CurrentAccountModel) WithErrorOnNondeterministicUpdateValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ErrorOnNondeterministicUpdate = value
	return c
}

func (c *CurrentAccountModel) WithEventTableValue(value tfconfig.Variable) *CurrentAccountModel {
	c.EventTable = value
	return c
}

func (c *CurrentAccountModel) WithExternalOauthAddPrivilegedRolesToBlockedListValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ExternalOauthAddPrivilegedRolesToBlockedList = value
	return c
}

func (c *CurrentAccountModel) WithExternalVolumeValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ExternalVolume = value
	return c
}

func (c *CurrentAccountModel) WithFeaturePolicyValue(value tfconfig.Variable) *CurrentAccountModel {
	c.FeaturePolicy = value
	return c
}

func (c *CurrentAccountModel) WithGeographyOutputFormatValue(value tfconfig.Variable) *CurrentAccountModel {
	c.GeographyOutputFormat = value
	return c
}

func (c *CurrentAccountModel) WithGeometryOutputFormatValue(value tfconfig.Variable) *CurrentAccountModel {
	c.GeometryOutputFormat = value
	return c
}

func (c *CurrentAccountModel) WithHybridTableLockTimeoutValue(value tfconfig.Variable) *CurrentAccountModel {
	c.HybridTableLockTimeout = value
	return c
}

func (c *CurrentAccountModel) WithInitialReplicationSizeLimitInTbValue(value tfconfig.Variable) *CurrentAccountModel {
	c.InitialReplicationSizeLimitInTb = value
	return c
}

func (c *CurrentAccountModel) WithJdbcTreatDecimalAsIntValue(value tfconfig.Variable) *CurrentAccountModel {
	c.JdbcTreatDecimalAsInt = value
	return c
}

func (c *CurrentAccountModel) WithJdbcTreatTimestampNtzAsUtcValue(value tfconfig.Variable) *CurrentAccountModel {
	c.JdbcTreatTimestampNtzAsUtc = value
	return c
}

func (c *CurrentAccountModel) WithJdbcUseSessionTimezoneValue(value tfconfig.Variable) *CurrentAccountModel {
	c.JdbcUseSessionTimezone = value
	return c
}

func (c *CurrentAccountModel) WithJsTreatIntegerAsBigintValue(value tfconfig.Variable) *CurrentAccountModel {
	c.JsTreatIntegerAsBigint = value
	return c
}

func (c *CurrentAccountModel) WithJsonIndentValue(value tfconfig.Variable) *CurrentAccountModel {
	c.JsonIndent = value
	return c
}

func (c *CurrentAccountModel) WithListingAutoFulfillmentReplicationRefreshScheduleValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ListingAutoFulfillmentReplicationRefreshSchedule = value
	return c
}

func (c *CurrentAccountModel) WithLockTimeoutValue(value tfconfig.Variable) *CurrentAccountModel {
	c.LockTimeout = value
	return c
}

func (c *CurrentAccountModel) WithLogLevelValue(value tfconfig.Variable) *CurrentAccountModel {
	c.LogLevel = value
	return c
}

func (c *CurrentAccountModel) WithMaxConcurrencyLevelValue(value tfconfig.Variable) *CurrentAccountModel {
	c.MaxConcurrencyLevel = value
	return c
}

func (c *CurrentAccountModel) WithMaxDataExtensionTimeInDaysValue(value tfconfig.Variable) *CurrentAccountModel {
	c.MaxDataExtensionTimeInDays = value
	return c
}

func (c *CurrentAccountModel) WithMetricLevelValue(value tfconfig.Variable) *CurrentAccountModel {
	c.MetricLevel = value
	return c
}

func (c *CurrentAccountModel) WithMinDataRetentionTimeInDaysValue(value tfconfig.Variable) *CurrentAccountModel {
	c.MinDataRetentionTimeInDays = value
	return c
}

func (c *CurrentAccountModel) WithMultiStatementCountValue(value tfconfig.Variable) *CurrentAccountModel {
	c.MultiStatementCount = value
	return c
}

func (c *CurrentAccountModel) WithNetworkPolicyValue(value tfconfig.Variable) *CurrentAccountModel {
	c.NetworkPolicy = value
	return c
}

func (c *CurrentAccountModel) WithNoorderSequenceAsDefaultValue(value tfconfig.Variable) *CurrentAccountModel {
	c.NoorderSequenceAsDefault = value
	return c
}

func (c *CurrentAccountModel) WithOauthAddPrivilegedRolesToBlockedListValue(value tfconfig.Variable) *CurrentAccountModel {
	c.OauthAddPrivilegedRolesToBlockedList = value
	return c
}

func (c *CurrentAccountModel) WithOdbcTreatDecimalAsIntValue(value tfconfig.Variable) *CurrentAccountModel {
	c.OdbcTreatDecimalAsInt = value
	return c
}

func (c *CurrentAccountModel) WithPackagesPolicyValue(value tfconfig.Variable) *CurrentAccountModel {
	c.PackagesPolicy = value
	return c
}

func (c *CurrentAccountModel) WithPasswordPolicyValue(value tfconfig.Variable) *CurrentAccountModel {
	c.PasswordPolicy = value
	return c
}

func (c *CurrentAccountModel) WithPeriodicDataRekeyingValue(value tfconfig.Variable) *CurrentAccountModel {
	c.PeriodicDataRekeying = value
	return c
}

func (c *CurrentAccountModel) WithPipeExecutionPausedValue(value tfconfig.Variable) *CurrentAccountModel {
	c.PipeExecutionPaused = value
	return c
}

func (c *CurrentAccountModel) WithPreventUnloadToInlineUrlValue(value tfconfig.Variable) *CurrentAccountModel {
	c.PreventUnloadToInlineUrl = value
	return c
}

func (c *CurrentAccountModel) WithPreventUnloadToInternalStagesValue(value tfconfig.Variable) *CurrentAccountModel {
	c.PreventUnloadToInternalStages = value
	return c
}

func (c *CurrentAccountModel) WithPythonProfilerModulesValue(value tfconfig.Variable) *CurrentAccountModel {
	c.PythonProfilerModules = value
	return c
}

func (c *CurrentAccountModel) WithPythonProfilerTargetStageValue(value tfconfig.Variable) *CurrentAccountModel {
	c.PythonProfilerTargetStage = value
	return c
}

func (c *CurrentAccountModel) WithQueryTagValue(value tfconfig.Variable) *CurrentAccountModel {
	c.QueryTag = value
	return c
}

func (c *CurrentAccountModel) WithQuotedIdentifiersIgnoreCaseValue(value tfconfig.Variable) *CurrentAccountModel {
	c.QuotedIdentifiersIgnoreCase = value
	return c
}

func (c *CurrentAccountModel) WithReplaceInvalidCharactersValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ReplaceInvalidCharacters = value
	return c
}

func (c *CurrentAccountModel) WithRequireStorageIntegrationForStageCreationValue(value tfconfig.Variable) *CurrentAccountModel {
	c.RequireStorageIntegrationForStageCreation = value
	return c
}

func (c *CurrentAccountModel) WithRequireStorageIntegrationForStageOperationValue(value tfconfig.Variable) *CurrentAccountModel {
	c.RequireStorageIntegrationForStageOperation = value
	return c
}

func (c *CurrentAccountModel) WithResourceMonitorValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ResourceMonitor = value
	return c
}

func (c *CurrentAccountModel) WithRowsPerResultsetValue(value tfconfig.Variable) *CurrentAccountModel {
	c.RowsPerResultset = value
	return c
}

func (c *CurrentAccountModel) WithS3StageVpceDnsNameValue(value tfconfig.Variable) *CurrentAccountModel {
	c.S3StageVpceDnsName = value
	return c
}

func (c *CurrentAccountModel) WithSamlIdentityProviderValue(value tfconfig.Variable) *CurrentAccountModel {
	c.SamlIdentityProvider = value
	return c
}

func (c *CurrentAccountModel) WithSearchPathValue(value tfconfig.Variable) *CurrentAccountModel {
	c.SearchPath = value
	return c
}

func (c *CurrentAccountModel) WithServerlessTaskMaxStatementSizeValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ServerlessTaskMaxStatementSize = value
	return c
}

func (c *CurrentAccountModel) WithServerlessTaskMinStatementSizeValue(value tfconfig.Variable) *CurrentAccountModel {
	c.ServerlessTaskMinStatementSize = value
	return c
}

func (c *CurrentAccountModel) WithSessionPolicyValue(value tfconfig.Variable) *CurrentAccountModel {
	c.SessionPolicy = value
	return c
}

func (c *CurrentAccountModel) WithSimulatedDataSharingConsumerValue(value tfconfig.Variable) *CurrentAccountModel {
	c.SimulatedDataSharingConsumer = value
	return c
}

func (c *CurrentAccountModel) WithSsoLoginPageValue(value tfconfig.Variable) *CurrentAccountModel {
	c.SsoLoginPage = value
	return c
}

func (c *CurrentAccountModel) WithStatementQueuedTimeoutInSecondsValue(value tfconfig.Variable) *CurrentAccountModel {
	c.StatementQueuedTimeoutInSeconds = value
	return c
}

func (c *CurrentAccountModel) WithStatementTimeoutInSecondsValue(value tfconfig.Variable) *CurrentAccountModel {
	c.StatementTimeoutInSeconds = value
	return c
}

func (c *CurrentAccountModel) WithStorageSerializationPolicyValue(value tfconfig.Variable) *CurrentAccountModel {
	c.StorageSerializationPolicy = value
	return c
}

func (c *CurrentAccountModel) WithStrictJsonOutputValue(value tfconfig.Variable) *CurrentAccountModel {
	c.StrictJsonOutput = value
	return c
}

func (c *CurrentAccountModel) WithSuspendTaskAfterNumFailuresValue(value tfconfig.Variable) *CurrentAccountModel {
	c.SuspendTaskAfterNumFailures = value
	return c
}

func (c *CurrentAccountModel) WithTaskAutoRetryAttemptsValue(value tfconfig.Variable) *CurrentAccountModel {
	c.TaskAutoRetryAttempts = value
	return c
}

func (c *CurrentAccountModel) WithTimeInputFormatValue(value tfconfig.Variable) *CurrentAccountModel {
	c.TimeInputFormat = value
	return c
}

func (c *CurrentAccountModel) WithTimeOutputFormatValue(value tfconfig.Variable) *CurrentAccountModel {
	c.TimeOutputFormat = value
	return c
}

func (c *CurrentAccountModel) WithTimestampDayIsAlways24hValue(value tfconfig.Variable) *CurrentAccountModel {
	c.TimestampDayIsAlways24h = value
	return c
}

func (c *CurrentAccountModel) WithTimestampInputFormatValue(value tfconfig.Variable) *CurrentAccountModel {
	c.TimestampInputFormat = value
	return c
}

func (c *CurrentAccountModel) WithTimestampLtzOutputFormatValue(value tfconfig.Variable) *CurrentAccountModel {
	c.TimestampLtzOutputFormat = value
	return c
}

func (c *CurrentAccountModel) WithTimestampNtzOutputFormatValue(value tfconfig.Variable) *CurrentAccountModel {
	c.TimestampNtzOutputFormat = value
	return c
}

func (c *CurrentAccountModel) WithTimestampOutputFormatValue(value tfconfig.Variable) *CurrentAccountModel {
	c.TimestampOutputFormat = value
	return c
}

func (c *CurrentAccountModel) WithTimestampTypeMappingValue(value tfconfig.Variable) *CurrentAccountModel {
	c.TimestampTypeMapping = value
	return c
}

func (c *CurrentAccountModel) WithTimestampTzOutputFormatValue(value tfconfig.Variable) *CurrentAccountModel {
	c.TimestampTzOutputFormat = value
	return c
}

func (c *CurrentAccountModel) WithTimezoneValue(value tfconfig.Variable) *CurrentAccountModel {
	c.Timezone = value
	return c
}

func (c *CurrentAccountModel) WithTraceLevelValue(value tfconfig.Variable) *CurrentAccountModel {
	c.TraceLevel = value
	return c
}

func (c *CurrentAccountModel) WithTransactionAbortOnErrorValue(value tfconfig.Variable) *CurrentAccountModel {
	c.TransactionAbortOnError = value
	return c
}

func (c *CurrentAccountModel) WithTransactionDefaultIsolationLevelValue(value tfconfig.Variable) *CurrentAccountModel {
	c.TransactionDefaultIsolationLevel = value
	return c
}

func (c *CurrentAccountModel) WithTwoDigitCenturyStartValue(value tfconfig.Variable) *CurrentAccountModel {
	c.TwoDigitCenturyStart = value
	return c
}

func (c *CurrentAccountModel) WithUnsupportedDdlActionValue(value tfconfig.Variable) *CurrentAccountModel {
	c.UnsupportedDdlAction = value
	return c
}

func (c *CurrentAccountModel) WithUseCachedResultValue(value tfconfig.Variable) *CurrentAccountModel {
	c.UseCachedResult = value
	return c
}

func (c *CurrentAccountModel) WithUserTaskManagedInitialWarehouseSizeValue(value tfconfig.Variable) *CurrentAccountModel {
	c.UserTaskManagedInitialWarehouseSize = value
	return c
}

func (c *CurrentAccountModel) WithUserTaskMinimumTriggerIntervalInSecondsValue(value tfconfig.Variable) *CurrentAccountModel {
	c.UserTaskMinimumTriggerIntervalInSeconds = value
	return c
}

func (c *CurrentAccountModel) WithUserTaskTimeoutMsValue(value tfconfig.Variable) *CurrentAccountModel {
	c.UserTaskTimeoutMs = value
	return c
}

func (c *CurrentAccountModel) WithWeekOfYearPolicyValue(value tfconfig.Variable) *CurrentAccountModel {
	c.WeekOfYearPolicy = value
	return c
}

func (c *CurrentAccountModel) WithWeekStartValue(value tfconfig.Variable) *CurrentAccountModel {
	c.WeekStart = value
	return c
}
