package resourceassert

import "github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"

func (c *CurrentAccountResourceAssert) HasAllDefaultParameters() *CurrentAccountResourceAssert {
	return c.
		HasAbortDetachedQueryString("false").
		HasAllowClientMfaCachingString("false").
		HasAllowIdTokenString("false").
		HasAutocommitString("true").
		HasBaseLocationPrefixEmpty().
		HasBinaryInputFormatString(string(sdk.BinaryInputFormatHex)).
		HasBinaryOutputFormatString(string(sdk.BinaryOutputFormatHex)).
		HasCatalogEmpty().
		HasCatalogSyncEmpty().
		HasClientEnableLogInfoStatementParametersString("false").
		HasClientEncryptionKeySizeString("128").
		HasClientMemoryLimitString("1536").
		HasClientMetadataRequestUseConnectionCtxString("false").
		HasClientMetadataUseSessionDatabaseString("false").
		HasClientPrefetchThreadsString("4").
		HasClientResultChunkSizeString("160").
		HasClientResultColumnCaseInsensitiveString("false").
		HasClientSessionKeepAliveString("false").
		HasClientSessionKeepAliveHeartbeatFrequencyString("3600").
		HasClientTimestampTypeMappingString(string(sdk.ClientTimestampTypeMappingLtz)).
		HasCortexEnabledCrossRegionString("DISABLED").
		HasCortexModelsAllowlistString("ALL").
		HasCsvTimestampFormatEmpty().
		HasDataRetentionTimeInDaysString("1").
		HasDateInputFormatString("AUTO").
		HasDateOutputFormatString("YYYY-MM-DD").
		HasDefaultDdlCollationEmpty().
		HasDefaultNotebookComputePoolCpuString("SYSTEM_COMPUTE_POOL_CPU").
		HasDefaultNotebookComputePoolGpuString("SYSTEM_COMPUTE_POOL_GPU").
		HasDefaultNullOrderingString(string(sdk.DefaultNullOrderingLast)).
		HasDefaultStreamlitNotebookWarehouseString("REGRESS").
		HasDisableUiDownloadButtonString("false").
		HasDisableUserPrivilegeGrantsString("false").
		HasEnableAutomaticSensitiveDataClassificationLogString("true").
		HasEnableEgressCostOptimizerString("true").
		HasEnableIdentifierFirstLoginString("true").
		HasEnableTriSecretAndRekeyOptOutForImageRepositoryString("false").
		HasEnableTriSecretAndRekeyOptOutForSpcsBlockStorageString("false").
		HasEnableUnhandledExceptionsReportingString("true").
		HasEnableUnloadPhysicalTypeOptimizationString("true").
		HasEnableUnredactedQuerySyntaxErrorString("false").
		HasEnableUnredactedSecureObjectErrorString("false").
		HasEnforceNetworkRulesForInternalStagesString("false").
		HasErrorOnNondeterministicMergeString("true").
		HasErrorOnNondeterministicUpdateString("false").
		HasEventTableString("snowflake.telemetry.events").
		HasExternalOauthAddPrivilegedRolesToBlockedListString("true").
		HasExternalVolumeEmpty().
		HasGeographyOutputFormatString(string(sdk.GeographyOutputFormatGeoJSON)).
		HasGeometryOutputFormatString(string(sdk.GeometryOutputFormatGeoJSON)).
		HasHybridTableLockTimeoutString("3600").
		HasInitialReplicationSizeLimitInTbString("10.0").
		HasJdbcTreatDecimalAsIntString("true").
		HasJdbcTreatTimestampNtzAsUtcString("false").
		HasJdbcUseSessionTimezoneString("true").
		HasJsonIndentString("2").
		HasJsTreatIntegerAsBigintString("false").
		HasListingAutoFulfillmentReplicationRefreshScheduleString("1440 MINUTE").
		HasLockTimeoutString("43200").
		HasLogLevelString("OFF").
		HasMaxConcurrencyLevelString("8").
		HasMaxDataExtensionTimeInDaysString("14").
		HasMetricLevelString("NONE").
		HasMinDataRetentionTimeInDaysString("0").
		HasMultiStatementCountString("1").
		HasNetworkPolicyEmpty().
		HasNoorderSequenceAsDefaultString("true").
		HasOauthAddPrivilegedRolesToBlockedListString("true").
		HasOdbcTreatDecimalAsIntString("false").
		HasPeriodicDataRekeyingString("false").
		HasPipeExecutionPausedString("false").
		HasPreventUnloadToInlineUrlString("false").
		HasPreventUnloadToInternalStagesString("false").
		HasPythonProfilerTargetStageEmpty().
		HasQueryTagEmpty().
		HasQuotedIdentifiersIgnoreCaseString("false").
		HasReplaceInvalidCharactersString("false").
		HasRequireStorageIntegrationForStageCreationString("false").
		HasRequireStorageIntegrationForStageOperationString("false").
		HasRowsPerResultsetString("0").
		HasSearchPathString("$current, $public").
		HasServerlessTaskMaxStatementSizeString("X2Large").
		HasServerlessTaskMinStatementSizeString(string(sdk.WarehouseSizeXSmall)).
		HasSsoLoginPageString("false").
		HasStatementQueuedTimeoutInSecondsString("0").
		HasStatementTimeoutInSecondsString("172800").
		HasStorageSerializationPolicyString(string(sdk.StorageSerializationPolicyOptimized)).
		HasStrictJsonOutputString("false").
		HasSuspendTaskAfterNumFailuresString("10").
		HasTaskAutoRetryAttemptsString("0").
		HasTimestampDayIsAlways24hString("false").
		HasTimestampInputFormatString("AUTO").
		HasTimestampLtzOutputFormatEmpty().
		HasTimestampNtzOutputFormatString("YYYY-MM-DD HH24:MI:SS.FF3").
		HasTimestampOutputFormatString("YYYY-MM-DD HH24:MI:SS.FF3 TZHTZM").
		HasTimestampTypeMappingString(string(sdk.TimestampTypeMappingNtz)).
		HasTimestampTzOutputFormatEmpty().
		HasTimezoneString("America/Los_Angeles").
		HasTimeInputFormatString("AUTO").
		HasTimeOutputFormatString("HH24:MI:SS").
		HasTraceLevelString("OFF").
		HasTransactionAbortOnErrorString("false").
		HasTransactionDefaultIsolationLevelString(string(sdk.TransactionDefaultIsolationLevelReadCommitted)).
		HasTwoDigitCenturyStartString("1970").
		HasUnsupportedDdlActionString("ignore").
		HasUserTaskManagedInitialWarehouseSizeString("Medium").
		HasUserTaskMinimumTriggerIntervalInSecondsString("30").
		HasUserTaskTimeoutMsString("3600000").
		HasUseCachedResultString("true").
		HasWeekOfYearPolicyString("0").
		HasWeekStartString("0")
}
