// Code generated by assertions generator; DO NOT EDIT.

package resourceassert

import (
	"testing"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
)

type NetworkPolicyResourceAssert struct {
	*assert.ResourceAssert
}

func NetworkPolicyResource(t *testing.T, name string) *NetworkPolicyResourceAssert {
	t.Helper()

	return &NetworkPolicyResourceAssert{
		ResourceAssert: assert.NewResourceAssert(name, "resource"),
	}
}

func ImportedNetworkPolicyResource(t *testing.T, id string) *NetworkPolicyResourceAssert {
	t.Helper()

	return &NetworkPolicyResourceAssert{
		ResourceAssert: assert.NewImportedResourceAssert(id, "imported resource"),
	}
}

///////////////////////////////////
// Attribute value string checks //
///////////////////////////////////

func (n *NetworkPolicyResourceAssert) HasNameString(expected string) *NetworkPolicyResourceAssert {
	n.AddAssertion(assert.ValueSet("name", expected))
	return n
}

func (n *NetworkPolicyResourceAssert) HasAllowedIpListString(expected string) *NetworkPolicyResourceAssert {
	n.AddAssertion(assert.ValueSet("allowed_ip_list", expected))
	return n
}

func (n *NetworkPolicyResourceAssert) HasAllowedNetworkRuleListString(expected string) *NetworkPolicyResourceAssert {
	n.AddAssertion(assert.ValueSet("allowed_network_rule_list", expected))
	return n
}

func (n *NetworkPolicyResourceAssert) HasBlockedIpListString(expected string) *NetworkPolicyResourceAssert {
	n.AddAssertion(assert.ValueSet("blocked_ip_list", expected))
	return n
}

func (n *NetworkPolicyResourceAssert) HasBlockedNetworkRuleListString(expected string) *NetworkPolicyResourceAssert {
	n.AddAssertion(assert.ValueSet("blocked_network_rule_list", expected))
	return n
}

func (n *NetworkPolicyResourceAssert) HasCommentString(expected string) *NetworkPolicyResourceAssert {
	n.AddAssertion(assert.ValueSet("comment", expected))
	return n
}

func (n *NetworkPolicyResourceAssert) HasFullyQualifiedNameString(expected string) *NetworkPolicyResourceAssert {
	n.AddAssertion(assert.ValueSet("fully_qualified_name", expected))
	return n
}

////////////////////////////
// Attribute empty checks //
////////////////////////////

func (n *NetworkPolicyResourceAssert) HasNoName() *NetworkPolicyResourceAssert {
	n.AddAssertion(assert.ValueNotSet("name"))
	return n
}

func (n *NetworkPolicyResourceAssert) HasNoAllowedIpList() *NetworkPolicyResourceAssert {
	n.AddAssertion(assert.ValueNotSet("allowed_ip_list"))
	return n
}

func (n *NetworkPolicyResourceAssert) HasNoAllowedNetworkRuleList() *NetworkPolicyResourceAssert {
	n.AddAssertion(assert.ValueNotSet("allowed_network_rule_list"))
	return n
}

func (n *NetworkPolicyResourceAssert) HasNoBlockedIpList() *NetworkPolicyResourceAssert {
	n.AddAssertion(assert.ValueNotSet("blocked_ip_list"))
	return n
}

func (n *NetworkPolicyResourceAssert) HasNoBlockedNetworkRuleList() *NetworkPolicyResourceAssert {
	n.AddAssertion(assert.ValueNotSet("blocked_network_rule_list"))
	return n
}

func (n *NetworkPolicyResourceAssert) HasNoComment() *NetworkPolicyResourceAssert {
	n.AddAssertion(assert.ValueNotSet("comment"))
	return n
}

func (n *NetworkPolicyResourceAssert) HasNoFullyQualifiedName() *NetworkPolicyResourceAssert {
	n.AddAssertion(assert.ValueNotSet("fully_qualified_name"))
	return n
}
